"""Article frontmatter and primary-source bibliography for A2 revision 157."""
BIB=r'''\bibitem{BrunsConca2003}
W.~Bruns and A.~Conca,
\emph{Gr\"obner bases and determinantal ideals},
arXiv:math/0302058v3 (2003), Lemma~2.5 and Theorem~2.4.

\bibitem{HenriquesVarbaro2016}
I.~Henriques and M.~Varbaro,
\emph{Test, multiplier and invariant ideals},
Adv. Math. \textbf{287} (2016), 704--732,
doi:10.1016/j.aim.2015.09.028; arXiv:1407.4324.

\bibitem{Vainsencher1982}
I.~Vainsencher,
\emph{Schubert calculus for complete quadrics},
in Enumerative Geometry and Classical Algebraic Geometry (Nice, 1981),
Progress in Mathematics \textbf{24}, Birkh\"auser (1982), 199--235.

\bibitem{Massarenti2020}
A.~Massarenti,
\emph{On the birational geometry of spaces of complete forms I:
collineations and quadrics},
Proc. Lond. Math. Soc. \textbf{121} (2020), 1579--1618,
doi:10.1112/plms.12377; arXiv:1803.09161v2, \S2.
'''
DISCLOSURE=r'''\paragraph{Revision 157.}
AI assistance was used in deriving and drafting the universal power-ideal
formula, its complete-quadric graph interpretation, the contact-divisor
and resolved-pencil statements, and their exact finite checks. Classical
determinantal, apolar and complete-quadric results are attributed at their
points of use. The proofs, rather than the computations, support the
general statements. No formal proof certification or journal endorsement
is claimed.

'''
II_TITLE='Reciprocal power ideals, complete quadrics, and pencil degenerations'
II_ABSTRACT=r'''The multiplication in a determinant-apolar algebra determines the
classical space of complete quadrics. More precisely, the coefficient
ideal of the $p$th power of a universal degree-one element is
$I_q^{h-s}I_{q+1}^s$, where $p=hq+s$ and $0\leq s<h$.
The equality holds over every complex algebra, including nonreduced
bases. The simultaneous graph closure of these powers is complete
quadrics as a scheme, independently of $h$. Its boundary divisors
principalize every power ideal, and their contact multiplicities along
a regular pencil recover the full spectral elementary-divisor data.
A projective incidence compactification carries flat limits of resolved
pencil curves and the original finite multiplication-failure algebras.
The apolar algebra occurs as the entire quadratic coefficient section
of a reciprocal normalization fibre. We retain the finite-flat binary
factorization theorem, the global squarefree conductor and branch
calculus, and the homological and collision results which provide this
normalization-fibre interpretation.'''
II_INTRO=r'''\section{Introduction}
\label{sec:divisor-introduction-v155}
Let $V$ be a complex vector space of dimension $n\geq2$.
A nondegenerate quadratic form determines all its exterior powers;
retaining their limits gives the classical space of complete quadrics.
We show that the same compactification is determined by multiplication
in one finite algebra arising from a common-divisor normalization fibre.
This supplies a global link between that fibre and the native geometry
of quadratic pencils, including nonreduced spectral schemes.

\subsection{The universal ideal formula}
Let $B_{n,h}$ be the apolar algebra of the $h$th power of the symmetric
determinant, with $(B_{n,h})_1=\Sym^2V$ and $h\geq1$.
For a symmetric matrix $A$ over a complex algebra $T$, denote its
corresponding degree-one element by $\ell_A$. Let $J_p(A)$ be the
ideal generated by the coordinates of $\ell_A^p$ in $(B_{n,h})_p$.
The first principal result, Theorem~\ref{thm:universal-power-v157}, is
\[
 J_p(A)=I_q(A)^{h-s}I_{q+1}(A)^s,
 \qquad p=hq+s,\quad0\leq s<h,\quad 0\leq p\leq nh.
\]
Here $I_q$ is the ideal of all $q$-minors and $I_0=T$; the second
factor is omitted when $s=0$. These are equalities of ordinary ideals
which commute with every base change, not merely closed-point or
valuation identities. In particular selected power-zero ideals are exact powers of all
Fitting ideals of $\coker A$. At $h=1$ the ideals
coincide, while for larger $h$ their powers need not have unique
ideal roots over a nonreduced base.

The proof compares two generating subrepresentations of
$\Sym^p(\Sym^2V^*)$. The apolar coefficient space consists exactly
of the even-row representations indexed by partitions of width at
most $h$. The same representations generate the balanced product of
minor ideals. Its inclusion in that bounded-width space follows from
torus weights; the opposite inclusion follows by balancing products
of principal minors. The needed symmetrization lemma and the
multiplicity-free decomposition are classical
\cite{BrunsConca2003,HenriquesVarbaro2016}. The universal comparison
is made before restriction to any family.

\subsection{A boundary determined by powers}
On $P=\Pj(\Sym^2V)$, take the simultaneous graph closure of the
nonzero powers $[\ell_A^p]$, for $1\leq p<nh$, initially over the
nondegenerate open. Theorem~\ref{thm:power-graph-v157} identifies it
with $\mathrm{CQ}(V)$ as a scheme over $P$. The product of its base
ideals is, up to an invertible factor,
$(I_2\cdots I_{n-1})^{h^2}$, so the Rees-algebra description of a
graph gives the isomorphism without taking a normalization.
The smoothness and flag strata of $\mathrm{CQ}(V)$ are the classical
complete-quadric results \cite{Vainsencher1982,Massarenti2020};
they are not asserted here as new properties of that variety.
The identification makes them intrinsic to the simultaneous power
maps of the reciprocal section.

Write $E_r$ for the boundary divisor of rank break $r$. We obtain
\[
 J_p\OO_{\mathrm{CQ}(V)}
     =\OO_{\mathrm{CQ}(V)}\left(-\sum_{r=1}^{n-1}(p-hr)_+E_r\right).
\]
This principalization determines the universal power-zero multiplier
ideals and thresholds as a consequence of the classical symmetric
rank-locus resolution. More importantly for pencils, the contact
divisors $D_r$ of the lifted member curve satisfy
\[
 \operatorname{mult}_xD_r=e_{r+1}(x)-e_r(x),
\]
where $0=e_1(x)\leq\cdots\leq e_n(x)$ are its Smith exponents.
Thus supported boundary contacts recover the full Segre data
(Theorem~\ref{thm:contact-Segre-v157}). A boundary point retains a
flag and quotient forms; it is the arc with contact multiplicities,
not the point alone, which retains the spectral exponents.

Proposition~\ref{prop:pencil-compactification-v157} constructs a
normal projective parameter space over the pencil Grassmannian. Its
flat universal Hilbert family records limits of resolved member
curves. The original finite multiplication-failure algebra pulls back
with its multiplication unchanged. This is a native equivariant
incidence compactification, not a properness assertion for a quotient
stack and not a classification of every limiting Hilbert fibre.

\subsection{The normalization-fibre origin}
For $E$ a complex vector space, the image of common-factor
multiplication
\[
 \Pj(\Sym^gE)\times\Gr(r,\Sym^{D-g}E)
             \longrightarrow\Gr(r,\Sym^DE),\qquad(f,J)\longmapsto fJ,
\]
has the marked-factor space as its finite normalization. At a
pure-power factor, its fibre has reciprocal algebra $F_{g,k}(W)$.
Theorem~\ref{thm:quadratic-section-v155} identifies its entire
quadratic coefficient section with $B_{n,h}$, for $n=\dim W$ and
$h=\lfloor g/2\rfloor$. The character, Hilbert function, length and
Gorenstein property of the determinant-apolar algebra are classical
inputs \cite{NagaokaWachi2024}; the equality of the fibre-section
ideal is what connects them to the geometric incidence.
The resulting length and Loewy-depth bounds apply to the whole fibre,
without identifying that fibre with its section.

We also prove and retain the binary finite-flat factorization theorem
on every exact-gcd stratum, the squarefree conductor formula and
all multiple branch intersections, the full block-arrangement Betti
table, the exact arbitrary-collision incidence atlas and the all-rank
double-root singular Fitting formula. The arbitrary-collision atlas
is a presentation, not a classification of all its local singularity
invariants. The quadratic section and universal power theory are
presented first; the full divisor geometry and technical descent
arguments follow with their complete proofs.

The companion paper proves the sharp unmarked inverse for every
quadratic pencil and its relative forms. References prefixed I refer
to that paper; all other references are internal. Its inverse supplies
the intrinsic interpretation of the native pencil used here. The native
congruence action is distinct from the full cotangent-coordinate action
under which all failure algebras have a common extreme limit. That
common point alone does not retain pencil data.

Our comparisons distinguish classical ingredients from their use for
normalization fibres and the power graph. In particular, the theorem
and proof text of \cite{Ballico93} has not been obtained; we draw no
historical priority conclusion from that documentary limitation.
'''
MASTER_ABSTRACT=r'''Every complex quadratic pencil is recovered from its unmarked,
ungraded finite multiplication-failure algebra at a sharp order.
The relative inverse recovers moving pencils and their actual source
bundles. We connect the divisor geometry of the first relation to
native pencil degenerations. The entire quadratic section of a
pure-power normalization fibre is a determinant-apolar algebra. Its
universal power-coefficient ideals are exact balanced products of
minor ideals over arbitrary complex bases. The simultaneous graph
of these powers is the classical space of complete quadrics,
independently of the determinant exponent. Its boundary contact
divisors recover all spectral elementary divisors of a regular pencil.
A projective incidence compactification carries resolved pencil curves
and the original finite failure family. We retain the binary finite-flat
factorization theorem, global squarefree conductor and branch calculus,
arbitrary-collision incidence atlas and homological fibre results.
This paired version includes both companion papers with unified
numbering and complete proofs.'''
MASTER_INTRO=r'''\section{Introduction}
\label{sec:introduction-v153}
The paper has two principal assertions about finite multiplication
failure. First, its abstract finite algebra recovers every quadratic
pencil after all markings have been forgotten. Second, the multiplication
of a distinguished section of its divisor-normalization fibre determines
a native global boundary, whose contacts recover pencil spectral data.
The two assertions are stated separately below; neither depends on
identifying a common extreme full-coordinate-change limit with a pencil
moduli point.

For $\dim V=n\geq3$ and $R\in\Gr(2,\Sym^2V)$, put
$N=\binom{n+1}{2}$, $p=N-2$ and $D=n+2p=n^2+2n-4$. Then
\[
 \mathfrak A_R^{[D]}=\C[t_{ij}]/
 \bigl((\det T)I_p(\gamma_R\Sym^2T)+\mathfrak m^{D+1}\bigr)
\]
determines $R$ up to congruence, even as an unmarked, ungraded algebra;
every smaller truncation is independent of $R$
(Theorems~\ref{thm:artin-local-inverse-v146} and
\ref{thm:sharp-finite-pencil}). The statement includes singular pencils.
Its global and relative forms recover moving subbundles and source
bundles. The first part gives these inverse theorems and their detailed
extensions without changing the finite invariant.

For a pure-power divisor, the normalization-fibre algebra $F_{g,k}(W)$
has an exact quadratic coefficient section $B_{n,h}$, the apolar algebra
of the $h$th power of a symmetric determinant. This section yields the
universal formula
\[
 J_{hq+s}(A)=I_q(A)^{h-s}I_{q+1}(A)^s,\qquad0\leq s<h,
\]
for every complex base algebra (Theorem~\ref{thm:universal-power-v157}).
The simultaneous graph of its powers is complete quadrics as a scheme,
not just after normalization (Theorem~\ref{thm:power-graph-v157}).
The complete-quadric boundary principalizes the ideals with multiplicities
$(p-hr)_+$; along a regular pencil the contact with its $r$th boundary
is the difference of consecutive Smith exponents
(Theorem~\ref{thm:contact-Segre-v157}).
Proposition~\ref{prop:pencil-compactification-v157} constructs a
projective parameter space carrying both resolved member curves and
the original finite failure algebra. The construction uses the native
congruence action, not the larger action on all cotangent coordinates.

The determinant-apolar representation theory, determinantal
symmetrization, and smooth complete-quadric geometry are classical
\cite{NagaokaWachi2024,BrunsConca2003,HenriquesVarbaro2016,
Vainsencher1982,Massarenti2020}. The contribution of the boundary
argument is the exact universal ideal identification and its
normalization-fibre and spectral interpretation. We also retain the
full binary finite-flat theorem, squarefree conductor and branch
stratification, arbitrary binary incidence atlas and fibre homology.
The distinction between an exact atlas and an analytic classification,
and between a fibre and its Gorenstein section, is maintained.

The companion reading versions separate the sharp reconstruction
argument from the divisor and power-graph argument. This complete
paired version retains their mathematical content with unified labels,
including the technical extensions in the appendices. Classical
comparisons appear at their point of use and in
Appendix~\ref{sec:introduction-v132}. The theorem-level comparison
with \cite{Ballico93} remains documentary-limited; no assertion of
anticipation or nonanticipation is based on unavailable text.
'''
