from pathlib import Path
p=Path('papers/General-Theta-Foundations-I-restart/r9-continuation-completion')
f=p/'main.tex';s=f.read_text(); a=s.index('\\begin{abstract}'); b=s.index('\\end{abstract}')+len('\\end{abstract}'); s=s[:a]+r'''\begin{abstract}
A prepared causal experiment acquires a geometry of conditional future responses. We prove a two-sided finite-resource theorem for experiments whose observable acquired measures admit global recursive covers. Their optimal online excess is governed by the largest continuation exponent across all information cuts; checkpoint excess is governed by the terminal exponent alone. This gives a necessary and sufficient criterion for their constant-factor agreement within the stated certificate class. The proof combines actual submeasure lower bounds with a candidate-moment recursion, allowing dependent reports, changing rank and singular acquisition. A positive-noise regression experiment has online exponent determined by observable rank rather than hidden dimension. A singular observation experiment exhibits a transition when a continuous future query changes the terminal geometry. We also establish a matched acquisition--memory--calibration law with an attained causal defect for progressive sensors. Numerical error and resource-certified experiment morphisms compose in the same scored task. Global characterization of arbitrary causal encoders is not assumed or asserted.
\end{abstract}'''+s[b:];s=s.replace('\\input{sections/09_noisy}','\\input{sections/10_serial_geometry}\n\\input{sections/09_noisy}\n\\input{sections/11_rank_and_singular}');f.write_text(s)
f=p/'sections/01_experiments.tex';s=f.read_text();a=s.index('The central resource transfer theorem');b=s.index('\\subsection{Kernels, interfaces');s=s[:a]+r'''The central result is Theorem~\ref{thm:serial}. Suppose the acquired response at cut $t$ has a positive-mass observable submeasure of exponent $s_t$, and a globally selectable cover of the same order is stable under the raw task updates. The stability requirement includes a Lyapunov envelope for all candidates, not just the exact trajectory or the code eventually chosen. Then, for one fixed terminal task and its full-history Bayes risk $B_T$,
\[
 R_\on(T,M)-B_T\asymp M^{-2/s_*},\qquad
 R_\cp(T,M)-B_T\asymp M^{-2/s_T},\qquad s_*=\max_t s_t.
\]
The entire family of actual continuation widths is equivalent in order to the online risk. Within this declared class, checkpoint and online compression match if and only if $s_*=s_T$. The theorem allows noninteger exponents, changing state dimension, dependent reports and expansive finite-horizon updates. Its proof constructs one $M$-label recursion at every cut; it does not assume that separately optimal checkpoint codebooks can be combined.

Two mechanisms make this possible. A conditional future response is a function of the information arriving after a cut. An earlier label must therefore choose a function, not merely a terminal scalar. Quantizing the actual dominated measure of these functions yields a common-task lower. Theorem~\ref{thm:cutduality} identifies the exact one-cut functional-coding problem, compares it with acquired Hilbert measures, and localizes it when physically shared side information prevents global product domination. Raw density and joint regeneration lemmas produce its common continuation laws. On the constructive side, global covers and a candidate Lyapunov bound control every inserted error under the actual report law, without independence or a free exact posterior register. The block transfer theorem, Theorem~\ref{thm:transfer}, retains its separate strength of time-uniform control under verified raw-block stability.

Theorem~\ref{thm:ranknoisy} verifies the central theorem from positive-noise correlated Gaussian kernels. Its successive observable ranks $r_j$ can change, and its largest rank $r$ is determined by the executable query family. It proves online excess $M^{-2/r}$ against checkpoint excess $M^{-2}$, even in an ambient hidden dimension $d>r$. A partial task statistic is not mislabeled a full predictive quotient: nuisance directions can still affect the suffix law. Theorem~\ref{thm:singularserial} instead starts from a Cantor-product preparation of total exponent $D$, obtained from its actual cylinder masses. A noisy continuation and continuous terminal query produce online excess $M^{-2/\max(D,1)}$. The terminal cut is essential when $D<1$. These two realizations are consequences of the same general theorem, not premises from which it is inferred.

Acquisition itself is a different optimization. A fixed exploration lower cannot be optimized by interchanging infima over its policy-dependent acquired law. Theorem~\ref{thm:adaptive} resolves this problem for progressive sensors with independent fair unread tails and arbitrary nonhomogeneous scales. The observed bit values do not alter future tail scales; this is why deterministic greedy allocation attains the optimum over all admitted adaptive allocations. Theorem~\ref{thm:joint} matches acquisition, retained memory, calibration and an attained simulation defect in one task. Theorem~\ref{thm:digital} gives a finite-bit feasible account, not a general computational lower. Theorem~\ref{thm:brier} preserves the sharp persistent-state law for ordinary filtering loss in sparse hidden-state models. A sequential-chart theorem and a full-rank noisy regression theorem are retained as intermediate consequences and independently checkable specializations.

The compatibility criterion requires both acquired observability and globally implementable update certificates. It does not derive the latter from bare one-cut widths for every causal experiment. The matched acquisition theorem does not solve unknown-kernel or arbitrary observation-dependent experimental design. Conditional projection, functional source coding, quantization, classical allocation and experiment comparison are explicitly credited in Section~\ref{sec:literature}. Supplement S~\cite{companion} is part of this same submission, supplied in full; it preserves the nonreset singular, stopped, calibration, output-grid and typed-interface proofs. It is not an external publication or a repository-only proof premise.

'''+s[b:];f.write_text(s)
f=p/'references.tex';s=f.read_text().replace('Proc. AAMAS (2026), 1201--1210.','arXiv:2602.08734, 2026 (accepted AAMAS 2026 author version).');f.write_text(s)
f=p/'sections/06_literature.tex';s=f.read_text();s+=r'''
\paragraph{Serial acquired exponents.}
Theorem~\ref{thm:serial} does not claim new small-ball quantization, Minkowski inequalities or linear error propagation. Its conclusion concerns the same scored experiment at every retained-state cut: observable acquired submeasures supply a lower of each exponent, while global inward covers and a candidate Lyapunov envelope supply a single causal construction. This establishes a conditional compatibility criterion and an explicit ratio of online to checkpoint excess. Neither an asymptotic decoder-side-information rate nor a separate optimal quantizer at each time alone supplies that recursion. The rank-sensitive example verifies the entire sequence of cuts, not only a terminal covariance. In the singular example the preparation geometry and the later task geometry have different exponents, so the maximum must include the final cut. The scope of the criterion is the stated raw-verifiable certificate class; it is not an unconditional duality theorem for all experiments.
''';f.write_text(s)
