"""R19 editorial audits and primary-source literature additions, emitted as ordinary files."""
from pathlib import Path

def write_literature(root:Path,old:Path)->None:
    text=(old/'sections/10_literature.tex').read_text()
    pos=text.index('Causal transport')
    text=text[:pos]+r'''Conditional convex order and measurable kernel selection have an established theory. Leskel\"a and Vihola\cite{leskela} prove conditional martingale-coupling results, including a kernel formulation. Our finite-target allocation proof does not claim measurable martingale selection as a new result. The serial restriction is that each next acquired law must be generated by the already retained law through a specified physical instrument. Sequential persuasion\cite{gan} studies serial signals with strategic obedience and commitment, whereas our external allocation has no separate strategic receiver: it is a nonstrategic finite-message allocation with the physical acquisition instrument fixed. A stationary signalling restriction is analogous to programme reuse, but no equivalence of the strategic and nonstrategic optimization problems is asserted. Dynamic information acquisition\cite{zhong} optimizes sequences of information choices under information costs; in that theory the admissible signal design can be much broader than garbling a fixed instrument. Here a hard label cap and a common reused programme impose different constraints. Neither comparison identifies Bayes plausibility with executable causal allocation.

''' +text[pos:]
    pos=text.index('Several approximation theories')
    text=text[:pos]+r'''The most direct computational neighbor is bounded finite-state-controller synthesis. Poupart and Boutilier\cite{poupart} optimize restricted stochastic controllers of POMDPs. Junges et al.\cite{junges} relate bounded randomized controllers to parameter synthesis for parametric Markov chains. Andriushchenko et al.\cite{andriushchenko} use oracle-guided inductive synthesis over finite-controller design spaces, including indefinite-horizon specifications; our exhaustive finite bound does not claim their algorithmic efficiency or scope. Amato, Bonet and Zilberstein\cite{amato} compare Mealy and Moore controller conventions, so the timing of report access and action output is part of the resource model, not innocuous notation. Our convention is a state-based action row followed by a report-dependent update row: the report dependence is Mealy-like in the update, whereas the action is tied to the current location. A different Moore/Mealy timing convention can change the charged number of locations. We do not claim that bounded-controller decidability or finite polynomial path constraints are new. Equation~\eqref{eq:finite_matrix} exhibits the fixed-proposal linear system, and Theorem~\ref{thm:finite_compiler} is positioned as a finite rational execution specialization. The general simultaneous theorem eliminates the same observation-dependent row across all occupied phases on compact predictive carriers. It does not remove the nonlinear optimization over the proposed conditional occupancies.

''' +text[pos:]
    pos=text.index('Grover and Dimitrakakis')
    text=text[:pos]+r'''Observation quantization itself is likewise not new. Kara, Bayraktar and Y\"uksel\cite{continuous} discretize continuous observations and use finite histories under controlled filter-stability conditions. Their policy near-optimality and learning results concern a different control benchmark. Theorem~\ref{thm:effective} preserves a fixed whole-controller alphabet and supplies lower as well as upper certificates relative to all Borel controllers at that budget. It needs a finite horizon, effective raw integrals, a common reconstruction and support data, but not filter contraction. Its exhaustive finite search is not a more efficient planning algorithm, and it does not subsume discounted or reinforcement-learning conclusions. Positive-instrument comparison, probability-row rounding and finite enumeration are standard ingredients; the proposed new assertion is their uniform, same-budget, exact-interface combination.

''' +text[pos:]
    text=text.replace('The new proposed mathematical contribution is the exact finite-support causal allocation frontier, its phase-compatible dual, the compact global finite-obstruction consequence, and their combination with explicitly counted implementation and distinct matching regimes.', 'The present principal addition is the effective completion of the exact allocation frontier, with common report reconstruction, support-resolved exact interfaces, explicit candidate counts and uniformly certified risk intervals at unchanged persistent cardinality. The exact finite-support allocation frontier, its phase-compatible dual, compact external obstruction and distinct matching regimes are retained and re-proved.')
    text=text.replace('a uniformly effective theory of all stationary compact-carrier optimizers,','a uniformly effective theory of arbitrary stationary compact-carrier optimizers without computation and support certificates,')
    (root/'sections/10_literature.tex').write_text(text)
    bib=(old/'references.tex').read_text()
    extra=r'''\bibitem{andriushchenko} R. Andriushchenko, M. \v{C}e\v{s}ka, S. Junges and J.-P. Katoen, \emph{Inductive synthesis of finite-state controllers for POMDPs}, Proc. Mach. Learn. Res. \textbf{180} (2022), 85--95.
\bibitem{amato} C. Amato, B. Bonet and S. Zilberstein, \emph{Finite-state controllers based on Mealy machines for centralized and decentralized POMDPs}, Proc. AAAI Conf. Artificial Intelligence \textbf{24} (2010), 1052--1058.
\bibitem{gan} J. Gan, R. Majumdar, G. Radanovic and A. Singla, \emph{Bayesian persuasion in sequential decision-making}, Proc. AAAI Conf. Artificial Intelligence \textbf{36} (2022), 5025--5033.
\bibitem{junges} S. Junges, N. Jansen, R. Wimmer, T. Quatmann, L. Winterer, J.-P. Katoen and B. Becker, \emph{Finite-state controllers of POMDPs using parameter synthesis}, Proc. Uncertainty in Artificial Intelligence 2018, Proc. Mach. Learn. Res. \textbf{R16} (2018), 518--528.
\bibitem{leskela} L. Leskel\"a and M. Vihola, \emph{Conditional convex orders and measurable martingale couplings}, Bernoulli \textbf{23} (2017), 2784--2807, doi:10.3150/16-BEJ827.
\bibitem{poupart} P. Poupart and C. Boutilier, \emph{Bounded finite state controllers}, Advances in Neural Information Processing Systems \textbf{16} (2003), 823--830.
\bibitem{continuous} A. D. Kara, E. Bayraktar and S. Y\"uksel, \emph{Near optimal approximations and finite memory policies for POMPDs with continuous spaces}, arXiv:2410.02895v2 (2025).
\bibitem{zhong} W. Zhong, \emph{Optimal dynamic information acquisition}, Econometrica \textbf{90} (2022), 1537--1582, doi:10.3982/ECTA17787.
'''
    bib=bib.replace(r'\end{thebibliography}',extra+r'\end{thebibliography}')
    (root/'references.tex').write_text(bib)

PIN='''Canonical: 18000b21e4bfd89180ccb069e46ac0f21621f34d.
Latest completed R18: da4a2a74d45f6ff21c4e7bdc7d7f8ae9daf7831a.
R18 ordinary source: 84ff7fc40dd16a316460aed23c126f156401d7b8; ordinary directory tree 2ae0b903d0a621eeec3525e8e143b12ec609cd83.
Latest external report: 1c70af9be79e93af9db5ea9cfc2a0271e8fe47ac; report blob 4dac5985a5f4b57e6807c2eba5073228bde16fb1.
Report path: GENERAL_THETA_FOUNDATIONS_I_RESTART_R18_CAUSAL_ALLOCATION_EXTERNAL_REFEREE_REPORT_R18.md.
R19 canonical-first-parent preservation merge: f33ff4c9a6dbb36677516c92f51706b4deacf3f0. Its second parent is the report head. All pre-existing files are retained at that parent, apart from the new R19 directory added here.
'''
MAJOR=[
('9.1','FSC positioning','Introduction; finite matrix system; literature section','Adds Poupart–Boutilier, Junges et al., Andriushchenko et al. and Amato–Bonet–Zilberstein; distinguishes state-based actions/report-dependent updates, fixed-proposal linear feasibility, nonlinear global synthesis and classical finite decidability.'),
('9.2','Exact criterion versus restatement','Central theorem and introduction','Says explicitly that the dual removes the common Borel kernel, not the law-valued trajectory. Adds an effective fixed-M frontier theorem instead of claiming the original compact criterion is a finite scalar invariant.'),
('9.3','Operational duals','Affine-witness lemma in Section 2','Proves affine test-span density; gives signed-score random test execution with its bound and budget; separates uniform limits and maxima from single executable continuations. Strict violation survives errors 2 epsilon / 2 n epsilon.'),
('9.4','Nontrivial finite common programme','Sharp reuse theorem in stationary section','Complete four-call raw experiment; feasible parallelogram; shared implementing row; optimal risks 1/2, 1/4, 0 at 3,4,5 labels. Randomized lower proved, not inferred from deterministic enumeration.'),
('9.5','External and internal clocks','Abstract, introduction, exact and effective statements','Separate interfaces throughout. New effective theorem permits phase flags; it does not rely on a universal M-n penalty.'),
('9.6','Conditional order and sequential design','Literature section','Adds Leskela–Vihola, Gan et al. and Zhong; specifies fixed physical instrument and serial hard-label constraints rather than treating conditional couplings or dynamic information choice as new.'),
('9.7','Finite obstruction is not effective','Obstruction remark and effective certificate corollary','Provides an arbitrarily delayed affine-prefix enumeration example. The new quantitative candidate bound concerns an effective finite programme cover, not a bound on affine-witness length in arbitrary compact data.'),
('9.8','Quantum scope','Both quantum theorems and scope section','Keeps fixed finite dimension, classical controller memory, finite POVM task. New no-reset/pure-state result is a raw trace-norm approximation statement, not a quantum-memory capacity theorem.'),
('9.9','Cardinality versus computation','First machine definition; central part (e); effective execution','Places the distinction before the first theorem; lists model, integration and cell-access certificates. Finite search may be prohibitive, and table bits are only feasible upper bounds.'),
('9.10','Title and compact qualification','Title, abstract, introduction','Retains the General Theta title and mother problem. Abstract explicitly says compact affine predictive carriers and names the effective completion, rather than changing the paper to a realization.'),
('11.2','Broader effective intrinsic frontier','Effective theorem and Gaussian/quantum/singular verification','Proves a finite, quantitatively convergent two-sided risk approximation at fixed horizon and whole-label budget, uniform over all Borel programmes. Gives explicit report mesh/tail errors, dyadic errors and finite candidate counts. Does not assert polynomial-time synthesis, a top-four impact verdict, or closure for arbitrary compact Borel kernels.')]
TECH=[
'Immediate intersection of occupied-phase legal actions after the machine definition.',
'Action-indexed common report spaces are reiterated adjacent to the central dual.',
'Corrected precisely: eta is a finite aggregate-occupancy measure and may have mass greater than one; it is not always a probability submeasure.',
'New affine-witness lemma proves the exact test-span density and execution qualifications.',
'Standard-Borel versions and arbitrary null-set completions stated in allocation proof.',
'Product topology and finite-coordinate separator stated explicitly.',
'Existing duplicate-atom argument retains marginal-flow equivalence, not the old labelled trajectory; preserved.',
'Existing proof uses concavity of the infimum of affine programme risks and actual chosen-action slack; preserved and distinguished from controller comparison.',
'Jensen defect renamed mathscr J_t; report kernel retains J_t.',
'Controller k retained where unambiguous; effective refinement h and dyadic Q separate index roles.',
'Finite relaxation displayed with gamma_t, atomic marginals, acquisition mixture and first-k inequalities.',
'Joint atom/action-weight existence for a fixed experiment stated; no measurable parameterized optimizer claim.',
'Clock condition explicitly remains equivalence of null sets, not a likelihood-ratio bound.',
'Legality at both occurrences of a reused label added to reference-trace explanation.',
'Distributional curvature measure renamed mu_f, separate from strong-concavity kappa.',
'Fixed affine Euclidean chart and norm comparison stated.',
'Original one-label/small-budget constant convention retained without deleting its proof.',
'Horizon- and task-specific B_n* repeated next to quantitative theorem scope.',
'Gaussian rank B_a=d explicitly reiterated, including larger report dimension.',
'Phase-specific available separating action included in the predictive interface, not runtime phase access.',
'Displayed Sylvester derivative of square root and derivative of normalized inverse congruence.',
'Original finite-dimensional POVM normalization, positivity restriction and constants retained.',
'Terminal m_n stopping/readout labels and immediate readout clarified.',
'Post-decision audit exclusion from the Markov cut relation reiterated.',
'Atom-to-every-center distance at least x_j/8 stated explicitly.',
'Complete stopped and scored law retained in common-task transfer.',
'Ideal-prefix first-mismatch and coordinate/readout distinction retained; new report-bound examples give uniform conditional certificates.',
'Algebraic sign and zero tests explicitly stated before support-preserving finite compiler use.',
'Only fixed-horizon finite paths checked; no recurrence or infinite-horizon solution claimed.',
'Given physical model and interpreter remain separate from programme bit bound.',
'Write-only early output and post-halt audit preserved; no readable uncharged register.',
'Manifest citation checks do not certify bibliographic completeness; audit records this.',
'Finite tests are not exhaustive separation proofs; limitation preserved.',
'Current native article is self-contained; archival W/V/U/T/S are preservation, not mandatory editorial reading.',
'All adaptive policies only within finite-action known-kernel interface and stated uniform assumptions.',
'Bayes/preparation specificity and lack of parameter-uniform minimax claim preserved.',
'Effective part accounts table/precision/scratch/time as feasible execution, not a matched full resource optimum.',
'Compact attainment retained only for external flow; new algorithm approximates values and need not attain a Borel stationary optimum.',
'Checkpoint policy-dependent acquisition baseline and compression stay in one infimum.',
'New citations checked against primary publication/preprint pages, including continuous-observation arXiv v2; inherited version-specific comparisons retained rather than silently updated.'
]

def write_documents(root:Path)->None:
    docs={}
    docs['README.md']='''# General Theta Foundations I — restart R19

The native paper is main.tex; build output is artifacts/General_Theta_Foundations_I_restart_R19.pdf. The topic and canonical control remain unchanged. The new principal result is an effective, uniformly two-sided approximation of the exact finite-label causal allocation frontier without normalized-filter contraction. All new proofs are in the native paper.

Read SUBMISSION_GUIDE.md, REFEREE_RESPONSE.md and PROOF_LEDGER.md. Complete previous papers are retained as companions W (R18), V (R15), U, T and S. They are not prerequisites for evaluating the native theorem. Build, delivery and regression evidence is not a proof or priority certificate.
'''
    docs['PINNED_INPUTS.md']='# Immutable inputs\n\n'+PIN
    docs['RESEARCH_CONTRACT.md']='# R19 effective frontier research and revision scope\n\n'+PIN+'''
The positive target is G1/G3: prepared causal experiment, executable future tests, predictive quotient, actual acquired law, finite causal allocation, resource-certified execution and same-task risk. R19 neither substitutes a specific realization nor reuses the old v96 manuscript. It retains the exact R18 theory and proves an effective completion on a broader-than-finite-report positive-instrument class, with explicit assumptions and no claim of universal effective synthesis.
'''
    docs['SUBMISSION_GUIDE.md']='''# Editorial reading order

Read the native abstract, introduction and central causal completion theorem first, then the new effective theorem and its two lemmas. The latter are the load-bearing new proofs: a uniform comparison of every Borel programme to one common report-cell programme, preservation of exact support paths, and finite risk certificates at fixed M. Read the two raw effective verifications and singular extension next. The finite worked threshold shows what the stationary dual enforces. The original exact allocation, geometry and quotient proofs remain in the native paper.

The exact geometric frontier remains law-valued. The effective theorem computes its value under positive-instrument approximation, support and computability certificates, not on arbitrary compact Borel inputs. Finite global enumeration may be enormous. No famous open problem, journal acceptance, independent priority, or complete optimal multi-resource region is claimed.

The title remains General Theta Foundations I: Acquired Geometry and Causal Resource Transfer. Historical full companions W/V/U/T/S provide preservation and optional context only; the current theorem should not require reading those pages. Audit tables and repository workflow records are outside the formal article.
'''
    docs['REFEREE_RESPONSE.md']='# Response to the R18 external report\n\n'+PIN+'''
We thank the referee for recognizing the exact compact-class allocation theorem while distinguishing it from an effective invariant. This revision responds positively with a new theorem, not a change of topic or a claim that polishing changes the journal-level assessment.

## Principal mathematical response

For support-resolved positive instruments we prove, at unchanged total persistent cardinality M and fixed horizon n, l-E_h-beta_Q <= R_aut <= u with u-l <= eta. The lower is uniform over every admissible Borel programme, not just the candidate set. Its key proof compares every Borel report row with a single phase-independent cell average using the same reconstruction measures. Positive direct-sum instrument error bounds control risk. Support equivalence preserves the exact finite-path graph; row rounding only removes edges. A finite dyadic candidate enumeration with explicit size therefore certifies both risk directions and returns a feasible programme. Model integration, output nets, cell access and numerical support conditions are genuine hypotheses, not hidden runtime oracles.

The new raw Gaussian verification permits nonmixing and deterministic transitions; the positive quantum verification permits unitary evolution and pure states. Neither uses normalized-filter contraction. Singular Cantor references and atomic tails yield explicit coarsening error curves, including a flagged changing-rank acquired law. The prior regular and blind matching laws are retained and re-proved. They are not recounted as new mathematics.

The new finite worked experiment has a sharp M=3,4,5 risk threshold with a nontrivial feasible common-row parallelogram and displayed implementing kernels. The affine-test lemma distinguishes genuine executable test scores, signed combinations, uniform limits and maxima. Controller-synthesis and conditional-information literature are explicitly compared.

## Major requests
'''
    for num,title,location,response in MAJOR:
        docs['REFEREE_RESPONSE.md']+=f'\n### {num}: {title}\n\n{response}\n\nLocation: {location}.\n'
    docs['REFEREE_RESPONSE.md']+='''
## Remaining mathematical scope

The effective theorem is a positive finite-dimensional, support-resolved result. Arbitrary compact affine Borel models are not rendered computable by compactness. No general affine-witness-length rate, efficient synthesis, unknown-kernel acquisition/minimax law, noncompact quotient classification, unrestricted infinite-horizon extension, or matched optimal programme/workspace/time/simulator region is asserted. These are substantive remaining goals, not reasons to replace the mother problem. Independent verification of correctness, novelty and general-journal significance remains necessary.
'''
    docs['REFEREE_COMMENT_CONCORDANCE.md']='# R18 comment concordance\n\n'+PIN+'\n## Forty technical/expository requests\n\n| No. | Revision or preserved safeguard |\n|---|---|\n'
    for i,t in enumerate(TECH,1):docs['REFEREE_COMMENT_CONCORDANCE.md']+=f'| {i} | {t} |\n'
    docs['REFEREE_COMMENT_CONCORDANCE.md']+='\nMajor requests 9.1–9.10 and substantive route 11.2 are addressed individually in REFEREE_RESPONSE.md. This table does not upgrade conditional results into universal closure.\n'
    docs['THEOREM_MAP.md']='''# Theorem dependency graph

Raw finite-dimensional or compact test-closed kernels -> quotient theorem in Appendix A -> experiment interfaces -> affine-witness lemma.

One-step barycentric allocation (classical convex order, re-proved) -> all-incoming calibration -> central external exact frontier.
Common stationary kernel -> simultaneous weak-star separation -> central autonomous exact frontier -> Bellman action/Jensen telescope. Fixed external widths plus weak continuity -> compact finite obstruction, not an effective modulus.

NEW: support-resolved raw positive instrument presentation -> common report-reconstruction lemma (uniform Borel comparison and exact finite-path equivalence) -> dyadic support lemma -> effective fixed-M theorem -> certified finite obstruction and baseline computation -> explicit programme/scratch/precision/time feasible accounts.

NEW: raw Gaussian gradient/tail bound OR raw quantum square-root trace-norm bound OR singular reference/atomic-tail bound -> effective presentation -> SAME effective theorem. None is a premise used to prove that theorem.

NEW: finite common-row linear system -> feasible parallelogram -> exact 3/4/5-state threshold.

Retained: actual-density and global-curvature bound + block sensitivity allocation -> regular matching law -> Gaussian/quantum regular verifications. Exact blind cut Markov lower -> actual-law quantization upper -> singular rate witnesses. Common complete scored law -> resource-certified simulator transfer. Real algebraic finite synthesis -> support-preserving rational execution.

Every existing substantive R18 theorem remains in the native proof graph. Historical standalone realizations remain independent unless explicitly cited as a witness; archive preservation is not a proof premise.
'''
    docs['PROOF_LEDGER.md']='''# Proof ledger

| Claim | Proof mechanism | Status and boundary |
|---|---|---|
| Affine witnesses are uniform test-span limits | Hahn–Banach/Riesz and equal-barycenter argument; explicit signed test lottery | Proved; uniform limits/maxima are not one finite-cost test |
| Exact external/autonomous causal frontier | Preserved full allocation/calibration/separation proofs | Proved under compact affine interface; Borel labels only in general |
| Uniform report reduction at unchanged M | Common phase-independent reconstruction, direct-sum base-norm contraction, support-path induction | New full proof; needs known support-resolved presentation |
| Uniform dyadic approximation | Floor plus supported residual, first mismatch | New continuous-class use; classical rounding tool; support only removed |
| Effective two-sided frontier | Finite programme cover, certified interval arithmetic, min-lower/min-upper inequality | New full proof, fixed finite n,M; explicit exponential candidate count, not efficient synthesis |
| Same-task excess computation | Separately certified same-experiment baseline interval; subtraction | Proved; full-history search is offline, not deployed memory |
| Gaussian effective verification | Uniform gradient bound plus explicit tail mass, all-input common support | Proved with computable nondegenerate Gaussian reports; transition may be nonmixing |
| Quantum effective verification | Positive effect, Sylvester square-root bound, trace-norm instrument control | Proved finite D; state need not be faithful; controller is classical |
| Singular effective extension | Cylinder oscillation and actual atomic tail mass | Proved with computable certificates; no ambient dimension rate asserted |
| Finite sharp shared programme | Exact parallelogram + legal label-type lower, common kernels | Proved for all randomized programmes of 3,4,5 labels in stated raw task |
| Regular/blind matching laws | Full R18 proofs retained with clarifications | Inherited, not counted as new; their stricter scopes unchanged |
| Common-task transfer and finite rational synthesis | Complete-law TV, product state, real algebraic finite constraints | Inherited/re-proved; not an optimal all-coordinate theorem |

The source contains continuous-parameter proofs. Regression tests only check selected finite consequences, arithmetic and implementation guards. This ledger is a proof audit, not a formal verification or an independent referee report.
'''
    docs['PROOF_AUDIT.md']='''# Proof audit

1. The central novelty claim is the uniform same-M completion, not merely finite enumeration. Its lower must compare against all Borel controllers. Lemma report_reduction does this before programme discretization.
2. Reconstruction is one measure per action/cell, independent of phase and physical state. A phase-specific posterior-weighted reconstruction would silently give multiple stationary programmes and is not used.
3. Use unnormalized positive instruments and the direct-sum base norm. No classical hidden trajectory is invented for quantum states, and no normalized-filter Lipschitz bound is needed.
4. Exact stopping is protected by support equivalence for every incoming positive state. Small total variation alone would not protect a probability-one deadline. Numerical cell errors must preserve support signatures if exact stopping is claimed.
5. Rounding only removes original edges. It may drop tiny probabilities; that is harmless to legality. Probability-one stopping is checked only to n, not via infinite recurrence.
6. min_g l_g <= min risk <= min_g u_g and min u-min l <= eta are justified with an index attaining min l. The risk certificate lower subtracts E+beta, while the upper programme runs directly on the original experiment.
7. Computable instrument integrals plus effective moduli, support tables and decision nets are input certificates. Exact equality tests on arbitrary computable reals are not used by graph legality.
8. Gaussian tails are retained as an extra cell. The tail error is twice actual mass, never a renormalized conditional law. No transition positivity is needed for the new effective theorem.
9. Quantum effect lower bound concerns E_y, not the evolving state's rank. CPTP outputs of pure inputs are legitimate; the norm estimate remains uniform.
10. Cantor and flagged atomic masses remain actual acquired masses. A singular reference alone is not asserted to imply every later posterior distribution is fractal.
11. Finite shared-row example proves the randomized lower by label types and row composition, not by claiming an exhaustive deterministic test covers all randomized rules.
12. All earlier exact/geometric/resource arguments remain with their original assumptions. No externally clocked rule is promoted to a free internal clock.

Unclosed: arbitrary Borel effectiveness, generally optimal search complexity and resource-description lower bounds, unknown-kernel learning and infinite-horizon extensions. Correctness and priority are subject to independent review; neither CI nor this audit certifies them.
'''
    docs['ASSUMPTION_MATRIX.md']='''# Assumption matrix

| Result | Primitive data | Actual-law/regularity data | Computation/interface data |
|---|---|---|---|
| Exact allocation | Prepared compact raw states with closed executable-test span; positive kernels | Compact affine quotient, specified weak-continuous acquired law where used | Finite horizon/actions; either external widths or one autonomous tuple; general Borel programme |
| Effective frontier | Finite-dimensional ordered base; positive mass-preserving instrument; bounded affine loss | Common report partition/reconstruction; computable base-norm error; support equivalence across active cells | Computable cell maps, support table, loss nets, executable cell access, dyadic programme enumeration |
| Gaussian effective | Finite hidden states, known stochastic transitions, nonsingular Gaussian reports | Explicit mean/covariance bounds, global gradient and actual tail bound | Computable parameters/integrals, explicit grid/tail classifier; no mixing/full-rank logit assumption |
| Quantum effective | Fixed finite D, CPTP maps, positive cube effect and fixed POVM | Effect gap kappa and upper K; uniform square-root trace-norm modulus | Computable entries/cell integrals; finite decision net; no state eigenvalue floor/no reset required |
| Singular effective | Cantor reference/Holder instrument or common-support countable reports | Explicit cylinder oscillation or uniform actual tail T_J | Effective support and integrals; finite flags exact |
| Regular matching | Compact finite affine chart, conventional curved task | Actual all-policy density cap, global covering, curvature, summable block sensitivity | Declared clocks; total labels distinct from bits |
| Blind matching | Actual compact prepared X; one capture then blind reports | Exact actual-law quantization; singular laws allowed | No recapture; post-decision audit; every intermediate alphabet counted |
| Simulator composition | Parameter-independent causal morphism | Complete stopped/scored law defect | Strategy/action/report/clock/readout compatibility; product simulator states |

No Gaussian/quantum realization theorem is used to establish a general theorem. Effective instrument assumptions do not replace actual acquired geometry in the exact frontier.
'''
    docs['COUNTEREXAMPLE_LEDGER.md']='''# Counterexample and sharpness ledger

- Phasewise convex order is insufficient for one programme: retained R18 obstruction and new feasible parallelogram show the missing simultaneous constraint.
- Fine report binning without a common reconstruction may pick a different row at each phase. The proof forbids that choice.
- Small TV alone permits rare premature halts. Support equivalence/edge removal is therefore separate from risk approximation.
- Uniformly tiny instrument error does not identify active support on arbitrary computable inputs. Supplied support data prevents undecidable zero tests being hidden in the algorithm.
- Affine moments alone accept the invalid split of delta_(1/2) into fair endpoint atoms. An affine-prefix enumeration can delay detection arbitrarily; compactness has no implied index rate.
- A terminal codebook does not preserve intermediate information: the full blind-transport bottleneck proof remains.
- External stage and internally stored stage are different resources. The finite threshold uses phase-revealing markers and does not import the common-null-set clock lower.
- Countably atomic acquired laws can have exponential quantization curves despite ambient dimension one; original witness retained.
- Allowed error tolerances alone are not lower-bound witnesses. Actual inaccessible offsets and actual early erasure are separately constructed in the retained four-resource corollary.
'''
    docs['RESOURCE_ACCOUNTING.md']='''# Resource account

| Coordinate | New effective construction | Lower/qualification |
|---|---|---|
| Persistent labels | Exactly the chosen M-state tuple, including start/stop/actions/programme reuse; no attached phase | Risk lower compares every Borel M-state tuple in the same interface |
| External widths | Explicit phase rows m_t, free stage supplied only by that model | Separate frontier, not M-n universal penalty |
| Raw acquisitions | Fixed n physical controller calls; scored audit separately counted | No free reconstruction calls: averaging is an offline identity |
| Report resolution | B_a bins, tails retained; raw d_(t,h) certificate | Risk loss <= H min(1,sum d); no acquired-law renormalization |
| Probability precision | Denominator Q=2^b, shared row rounded once | Risk loss <= H min(1,n(A+M)/Q); only support removed |
| Decisions | K_rho loss-net codes | Uniform loss error rho, separately charged output encoding |
| Programme | O(P log(Q+1)+M log(K+1)+M+log M)+classifier+output tables | Feasible description upper; physical model/integrator/interpreter not silently included |
| Scratch | b, row indices/sums, classifier and readout workspace | Erased before next call; no retained random seed |
| Runtime | Exactly b fresh random bits per row; finite scans + physical report/classifier costs | Dyadic sampling no rejection loop; offline enumeration may be prohibitive |
| Planning | At most M 2^M K^M (Q+1)^P candidates with certified risk calculations | Computable finite bound, not polynomial or optimal search complexity |
| Numerical reports | Ideal-prefix mismatch chi with support signature preserved | Adds H chi; exact deadline would not follow from mismatch bound alone |
| Causal simulator | Explicit strategy lift and complete scored law; R_sim times M states | Adds H epsilon, no reverse lower from a one-way simulator |

Regular and blind acquired-geometry laws and attained N,M,delta,epsilon task extensions remain with full proofs. A complete jointly optimal programme/workspace/time/simulator region remains unproved.
'''
    docs['PIPELINE_DERIVATION.md']='''# Native derivation pipeline

1. Read prepared kernels through executable future tests. Establish the compact predictive quotient, representative-independent positive instrument and minimality relative to the legal test interface.
2. At every deployed cut compute only certificate-level conditional barycenters; the machine does not store them for free. The next acquisition law is generated by its retained law and chosen legal actions.
3. Prove the finite-target barycentric criterion and serial external realization. For stationary reuse use one common report row, producing the simultaneous support function after the phase sum.
4. Telescope actual action slack and pooling Jensen defects against the same Bellman task baseline. This is the exact risk invariant; do not minimize baseline and compression separately.
5. NEW: construct a finite raw report experiment with a common phase-independent reconstruction. For any Borel tuple average its row once. Direct-sum positivity controls the whole-law risk; support equivalence controls its exact finite paths.
6. NEW: round common rows on their original support. Dyadic tables preserve the same M and exact deadline. Enumerate all such tables and compute certified actual risk intervals from finite cell instruments.
7. NEW: combine R <= R_h <= R+E and R_h <= R_G <= R_h+beta. Thus min lower -E-beta <= R <= min upper, with explicit finite list and interval width. This compares all Borel programmes, not only the list.
8. Verify raw Gaussian gradient/tails, raw noncommuting quantum trace-norm modulus, Cantor cylinders and countable tails. No filter contraction enters these verifications. Actual retained/acquired laws still determine the exact invariant.
9. Give the finite sharp shared-row threshold and operational test-score interpretation. Keep the existing regular and singular matching consequences with their original scopes.
10. Compose calibrated/numerical/simulation errors in the same scored task; charge product simulator states, report precision, programme, scratch and physical calls separately.

Continuous proofs precede finite regression. The latter verifies selected arithmetic consequences and support-implementation examples only.
'''
    docs['SCOPE_AUDIT.md']='''# Scope audit

The mother problem and title are unchanged. The manuscript contains a general exact compact affine allocation theorem and a new effective completion on a explicitly presented positive-instrument class. The class contains continuous-report known Gaussian experiments without mixing and finite-dimensional noncommuting instruments without resets, as well as certified singular and atomic report classes. Realizations verify the theorem and do not define it.

The effective statement does not assume an already available posterior register and keeps the whole M-label stationary programme. It is uniform over all Borel programmes in the fixed interface. It is not a universal closed-form scalar geometry formula; it computes the exact law-valued frontier's value using explicit finite certificates. Its lower bound concerns risk at fixed M, not optimal bits/workspace/time. It is not an affine-witness-length rate for arbitrary compact-data enumerations.

The experiment and its integration/support moduli are known. Bayes preparation is not parameter-uniform frequentist sufficiency or minimax learning. Finite horizons are not unbounded stopping or infinite horizons. Positivity of quantum effects does not imply a claim about arbitrary quantum memory or unbounded operators. Reused phase conditional states are certificate variables, never visible runtime phase/state registers. Temporary report access is erased before the next call.

Remaining substantive gaps: arbitrary noncompact or non-effective Borel quotients; finite certificates without support/integration data; a broadly matched all-computational-resource region; unknown-kernel adaptive learning; infinite-horizon optimality and a general online/checkpoint equivalence classification. No mathematical breakthrough is inferred from repository organization, compilation or number of tests. New proof correctness and priority require independent review.
'''
    docs['NOTATION_AUDIT.md']='''# Notation audit

J_t is the report law; mathscr J_t is now the pooling Jensen defect. mu_f is the distributional curvature measure; kappa is a task/effect lower constant specified locally. k denotes a controller row in exact allocation; Q=2^b is the probability denominator; h is a supplied report-refinement index (or a stated mesh size in an explicit realization). eta without subscripts in the effective theorem is a risk-enclosure tolerance; eta_(z,a) in the stationary dual is an aggregate occupancy measure, not necessarily probability mass <=1.

R is risk, mathsf R_(a,b) a common report reconstruction, and R_sim the simulator count in the resource table. Physical base B and report-bin counts B_a have distinct typefaces. H bounds the loss, while Hermitian effects H_i have indices. B_n* is the full-history baseline for the same horizon/task. N may include a scored post-halt audit; n counts the engine/controller transitions as explicitly stated.

No label count is silently converted into total bit complexity. No affine or polyhedral convex test is silently interpreted as a physically free scored continuation.
'''
    docs['HISTORY_COVERAGE.md']='# Historical coverage and preservation\n\n'+PIN+'''
Directly inspected in this revision: the latest R18 external report, R18 native mathematical source (all eleven sections, central proofs and references), current audit/derivation/build materials, four canonical controls and the foundational outline sections governing the original G1/G3 target; relevant inherited R15/R18 resource and realization arguments. New neighboring literature was checked at primary publication/preprint pages. The downloaded R18 packet provides the retained restart source/build chain used for independent compilation.

The full R18/review tree was preserved as a merge parent and base tree, including all old root papers and restart directories. The four control files are not edited. The new manuscript re-proves the R18 arguments it uses; W is the complete R18 article, V the complete R15, with U/T/S retained. Old review branches, independent realization branches and the frozen archive are not updated.

Preservation is not a fresh proof audit of every v1–v96 lemma, every old referee report or each independent realization. That exhaustive mathematical rereading is not claimed. Ordered-measurement, finite-action, streaming-memory and other standalone lines retain independent status; none is used in reverse to prove the new general theorem. The newly effective regime unifies classical and finite-dimensional positive-instrument execution at fixed labels, while older model-specific conclusions outside its hypotheses remain independent.
'''
    docs['LITERATURE_COMPARISON.md']='''# Literature comparison and consulted primary sources

The new claim is a uniform same-cardinality, support-preserving completion of the exact causal frontier for positive instruments, not the invention of finite-state controllers, conditional means, report quantization, convex order or real algebraic decidability.

| Work | Existing result relevant here | R19 distinction |
|---|---|---|
| Strassen; Leskela–Vihola (Bernoulli 23, 2784–2807, 2017) | Martingale/conditional convex-order coupling and measurable kernel results | Serial actual acquisition and one common reused programme; no new one-step martingale-coupling claim |
| Poupart–Boutilier, NIPS 16 (2003) | Bounded stochastic finite-state controller optimization | Explicit fixed-proposal dual and same-M all-Borel certified risk frontier, not a claim that bounded controllers are new |
| Junges et al., UAI/PMLR R16 (2018), 518–528 | Finite-state controller/parametric Markov synthesis connection | Compact predictive moment elimination; continuous-instrument uniform approximation; finite rational decidability credited |
| Andriushchenko et al., PMLR 180 (2022), 85–95 | Oracle-guided inductive FSC synthesis, including indefinite-horizon specifications | Explicit exhaustive same-M continuous-report risk certificates; no claimed algorithmic improvement or infinite-horizon extension |
| Amato–Bonet–Zilberstein, AAAI 24 (2010), 1052–1058 | Mealy versus Moore controller conventions | Report/action timing fixed explicitly; label counts depend on the declared interface |
| Gan et al., AAAI 36 (2022), 5025–5033 | Sequential persuasion with strategic receiver and commitment | Non-strategic fixed-instrument finite-message flow; shared programme restrictions do not identify the two optimization problems |
| Saldi–Yuksel–Linder, arXiv 1710.07009v1 | Finite-model approximation for discounted partially observed control | Fixed finite n and whole M labels; no claim to subsume discounted control results |
| Kara–Bayraktar–Yuksel, arXiv 2410.02895v2 (17 Jan 2025) | Observation discretization plus finite histories, controlled filter stability and Q-learning | No normalized-filter contraction, same-M complete stationary programme, uniform lower/upper certificates; not an efficient learning result |
| Zhong, Econometrica 90 (2022), 1537–1582 | Dynamic information acquisition with information costs | Fixed physical instruments, hard label budgets and programme compatibility, not freely chosen signal design |

Primary metadata consulted 9 October 2026: https://math.aalto.fi/~lleskela/paper018.html ; https://proceedings.mlr.press/r16/junges18a.html ; https://papers.nips.cc/paper_files/paper/2003/hash/4c5bcfec8584af0d967f1ab10179ca4b-Abstract.html ; https://arxiv.org/abs/2410.02895 ; https://arxiv.org/abs/1710.07009 ; https://onlinelibrary.wiley.com/doi/abs/10.3982/ECTA17787 . The three additional directly requested comparisons were checked at https://proceedings.mlr.press/v180/andriushchenko22a.html ; https://ojs.aaai.org/index.php/AAAI/article/view/7748 ; https://ojs.aaai.org/index.php/AAAI/article/view/20434 . Some publisher pages required indexed primary-page text; no claims are based on secondary reviews. R18's existing version-specific bibliography remains in place. Its earlier metadata is preserved, not represented as a newly exhaustive bibliographic re-audit.

This is a targeted comparison, not independent priority certification. Bibliography resolution and citation-use checks establish source integrity, not literature completeness. The native article states substantive distinctions and limitations rather than claiming all adjacent work is superseded.
'''
    docs['BUILD_PROTOCOL.md']='''# Reproducible build protocol

The source commit contains the ordinary manuscript, complete proofs, audit files and manifest. prepare_r19.py is a deterministic editorial reproduction from immutable R18 plus explicit new files; it is not needed for ordinary compilation and never edits the R18 directory. Its emitted ordinary files are committed before compilation. Bootstrap material is not substituted for an ordinary-source submission.

Run python3 verify.py; python3 regression.py; python3 -O regression.py; then python3 build.py --source-sha ACTUAL_SOURCE_COMMIT --expected-tree ACTUAL_ORDINARY_TREE --output /external/output --receipt /external/receipt.json. Native compilation builds two isolated copies, three pdflatex passes each, checks active recorder inputs, requires within-environment byte identity, and rejects undefined references or overfull boxes. The complete build separately rebuilds unchanged R18 and its entire V/U/T/S chain. Run an independent rebuild from the actual remote artifact ZIP, outside a read-only source tree.

Separate source, artifact and final evidence-only commits. Archive packet binding records the actual source/artifact identities. Final verification only adds evidence; it cannot change a PDF or mathematical source under an old receipt. Cross-engine PDF bytes may differ; report actual normalized-text/page/render comparisons, never claim byte identity when absent. The build scope is R19 and retained W/V/U/T/S, not all repository papers. Finite regressions and render checks do not prove continuous-parameter mathematics.
'''
    for name,text in docs.items():
        (root/name).write_text(text if text.endswith('\n') else text+'\n')
