#!/usr/bin/env python3
"""Finite exact regressions; the continuum classification has a written proof."""
from __future__ import annotations
import copy
import json
from math import comb
import sympy as s
from curve_geometry import classify, certify, verify, INPUT
from covariance_metric import system, inner, covariance
from support_geometry import support_data, support, hermitian_basis
from matrix_metric import matrix_to_json

checks=0; negatives=0

def check(value, text):
    global checks
    if not bool(value):raise RuntimeError(text)
    checks+=1

def rejects(fn):
    global negatives
    try:fn()
    except (ValueError,TypeError,KeyError,RuntimeError):negatives+=1;return
    raise RuntimeError('negative control accepted')

def jet(e,h):
    return {'schema':INPUT,'dimension':e[0].rows,'outcomes':len(e),
        'effects':[matrix_to_json(x) for x in e], 'tangent':[matrix_to_json(x) for x in h]}

def zero_matrix(x):return all(s.simplify(v)==0 for v in x)

def in_range(e,h):
    basis,gram,stiff=system(e)
    rhs=s.Matrix([inner(b,h) for b in basis])
    return stiff.rank()==stiff.row_join(rhs).rank()

I=s.eye(2); Z=s.diag(1,-1); X=s.Matrix([[0,1],[1,0]]); Y=s.Matrix([[0,-s.I],[s.I,0]])
P=(I+Z)/2
families=[ [P,I-P], [P/2,(I-P)/2,(I+X)/4,(I-X)/4],
          [(I+Z/3)/3,(I+X/4)/3,(I-Z/3-X/4)/3],
          [P/2,P/2,I-P], [P,I-P,s.zeros(2)] ]
records=[]
for e in families:
    for g in [X,Y,Z,X+Y+2*Z]:
        h=[(s.I*(g*a-a*g)).applyfunc(s.expand) for a in e]
        c=classify(e,h); old=support_data(e,g)
        check(c['in_span']==in_range(e,h),'support/range equivalence')
        check(c['in_span']==old['in_span'],'unitary restriction')
        projected=support_data(e,c['gamma']-g)['complement']
        check(projected==s.zeros(2),'generator quotient normalization')
        check(c['residual']==old['complement'],'unitary residual exact')
        raw=jet(e,h); out=certify(raw); check(verify(raw,out)['exact_replay'],'certificate replay')
        check(out['finite_use_regime']==('higher_order_undetermined' if old['stationary'] else old['regime']),'zero-jet handling')
        records.append(out['finite_use_regime'])

# Nonunitary first jet generated by normalization of independently perturbed factors.
t=s.symbols('t',real=True)
A=[P/s.sqrt(2),(I-P)/s.sqrt(2),(I+X)/(2*s.sqrt(2)),(I-X)/(2*s.sqrt(2))]
# Choose B=-i A_j G_j and correct its stacked Hermitian normalization derivative.
Gs=[Y,2*Y,3*Z,X]
B0=[-s.I*a*g for a,g in zip(A,Gs)]
D=sum((a.adjoint()*b+b.adjoint()*a for a,b in zip(A,B0)),s.zeros(2))/2
B=[s.simplify(b-a*D) for a,b in zip(A,B0)]
e=[s.simplify(a.adjoint()*a) for a in A]
h=[s.simplify(a.adjoint()*b+b.adjoint()*a) for a,b in zip(A,B)]
c=classify(e,h)
check(c['in_span']==in_range(e,h),'nonunitary first jet range')
# Check the full kernel pairing for an off-support Hermitian direction.
for T in hermitian_basis(2):
    aa=support_data(e,T)['complement']
    Ps=[support(a) for a in e]
    k0=[s.I*(p*aa-aa*p) for p in Ps]
    mean=sum(k0,s.zeros(2))/len(e);kt=[v-mean for v in k0]
    check(s.simplify(inner(h,kt)+2*s.trace(aa*c['gamma']))==0,'general pairing sign')

# All diagonal missing-support blocks must vanish, including a zero effect.
bad_e=[P,I-P,s.zeros(2)];bad_h=[-I,s.zeros(2),I]
rejects(lambda:classify(bad_e,bad_h))

# Explicit rank-opening rational curve; not a unitary orbit.
U=s.Matrix([[1-t*t,2*t],[-2*t,1-t*t]])/(1+t*t)
e1=s.simplify((1-t*t)*U*P*U.T+t*t*I/2)
check(zero_matrix(U.T*U-I),'rational unitary chart')
h1=s.simplify(e1.diff(t).subs(t,0))
check(classify([P,I-P],[h1,-h1])['regime']=='linear','rank-opening linear branch')
check(s.simplify(e1.det()-t*t*(2-t*t)/4)==0,'rank-opening determinant')
check(s.factor(s.trace(e1))==1,'rank-opening trace')

# Horizontal normalized factors: prove identities exactly in one rational chart.
# A and B columns are orthogonal, B*B=I, so normalized E_j are rational.
aa=s.Matrix.vstack(I/s.sqrt(2),I/s.sqrt(2))
bb=s.Matrix.vstack(Z/s.sqrt(2),-Z/s.sqrt(2))
check(zero_matrix(aa.adjoint()*bb),'horizontal factor')
r=(aa+t*bb)/s.sqrt(1+t*t)
check(zero_matrix(s.simplify(r.adjoint()*r-I)),'normalized horizontal chart')
check(zero_matrix(s.simplify(r.adjoint()*r.diff(t))),'horizontal curve gauge')
check(zero_matrix(s.simplify(r.diff(t).adjoint()*r.diff(t)-I/(1+t*t)**2)),'horizontal derivative energy')
he=[I/2,I/2];hh=[Z,-Z]
check(classify(he,hh)['regime']=='square_root','nonunitary horizontal jet')

# General logical derivative identities on a projective qubit code.
# |0_L>=|+y>|0_flag>, |1_L>=|-y>|1_flag>. For PVM supports,
# choose generator X and +/- X states instead to make gap 2.
plus=s.Matrix([1,1])/s.sqrt(2);minus=s.Matrix([1,-1])/s.sqrt(2)
flag0=s.Matrix([1,0]);flag1=s.Matrix([0,1])
J=s.Matrix.hstack(s.kronecker_product(plus,flag0),s.kronecker_product(minus,flag1))
g=X; h=[s.I*(g*P-P*g),-s.I*(g*P-P*g)]
Ps=[P,I-P];Bs=[p*hj*(I-p/2) for p,hj in zip(Ps,h)]
check(zero_matrix(sum((p*b for p,b in zip(Ps,Bs)),s.zeros(2))+s.I*g),'canonical factor generator')
# For outcome 0 recover flags unchanged, for outcome 1 apply Z to flags.
# Amplitudes are 1/sqrt(2), with the minus-state outcome-1 sign corrected.
Rs=[I,Z]
left=s.zeros(2)
for j in range(2):
    row=s.Matrix([[1,0]]) if j==0 else s.Matrix([[0,1]])
    L=s.kronecker_product(row*Ps[j],I)
    Ldot=s.kronecker_product(row*Bs[j],I)
    check(zero_matrix(Rs[j]*L*J-I/s.sqrt(2)),'PVM correction')
    left+=Rs[j]*Ldot*J/s.sqrt(2)
check(zero_matrix(left+s.I*(J.adjoint()*s.kronecker_product(g,I)*J)),'general corrected first derivative')

# Exact Bernoulli laws at endpoints and in the interior, no simulation.
bern=0
for n in [1,2,3,5,8,12]:
    for p in [s.Rational(0),s.Rational(1,8),s.Rational(1,2),s.Rational(7,8),s.Rational(1)]:
        for q in [s.Rational(0),s.Rational(1,4),s.Rational(1,2),s.Rational(3,4),s.Rational(1)]:
            l1=sum(abs(comb(n,j)*(p**j*(1-p)**(n-j)-q**j*(1-q)**(n-j))) for j in range(n+1))
            check(l1*l1>=min(1,n*(p-q)**2)/128**2,'finite product lower');bern+=1

raw=jet([P,I-P],h);out=certify(raw)
for key in ['finite_use_regime','support_generator','generator_residual','tangent_in_covariance_range',
            'physical_protocol_executed','curvature_bound_computed','recovery_synthesized','input_sha256']:
    bad=copy.deepcopy(out);bad[key]='tampered';rejects(lambda bad=bad:verify(raw,bad))
for mutation in [dict(schema='wrong'),dict(dimension=True),dict(outcomes=1),dict(extra=1),dict(tangent=[]),dict(effects=[])]:
    bad=copy.deepcopy(raw);bad.update(mutation);rejects(lambda bad=bad:certify(bad))
rejects(lambda:certify(raw,max_dimension=1))
bad=copy.deepcopy(raw);bad['tangent'][0][0][0]='0.1';rejects(lambda:certify(bad))
zero=certify(jet([P,I-P],[s.zeros(2),s.zeros(2)]))
check(zero['finite_use_regime']=='higher_order_undetermined' and zero['theorem'] is None,'zero derivative not stationary')
# Rational sufficient-budget algebra with pi bounded above by 4.
for n in [1,2,10,100]:
    for u in [s.Rational(1,1000),s.Rational(1,100)]:
        delta=s.Rational(2);kappa=s.Rational(4);m=min(n,int(s.floor(1/(u*delta))))
        x=m*u*delta;z=min(1,n*u*delta)
        check(z/2<=x<=1,'integer call ledger')
        nu=u*delta/32;outside=z/64
        check(2*outside+2*m*nu<=x/4,'conservative rational control budget')
        check(m*kappa*u*u<=x/8,'curvature budget with pi<4')
print(json.dumps({'schema':'gtf85.curve-regressions/1','status':'success',
    'positive_checks':checks,'negative_controls':negatives,'exact_bernoulli_pairs':bern,
    'unitary_cases':len(records),'nonunitary_jet_checked':True,'rank_opening_checked':True,
    'horizontal_normalization_checked':True,'logical_first_derivative_checked':True,
    'zero_tangent_not_stationary':True,'physical_protocol_executed':False,
    'general_recovery_synthesized':False,'continuum_proof_by_replay':False},indent=2,sort_keys=True))
