#!/usr/bin/env python3
"""Exact audits of the displayed v163 equations, not general proof certificates."""
from __future__ import annotations
import argparse, hashlib, itertools, json, math, subprocess, sys
from pathlib import Path
import sympy as S
HERE=Path(__file__).resolve().parent

def require(condition:bool, description:str)->None:
    if not condition:raise AssertionError(description)
def same_ideal(left,right,variables):
    return S.groebner(left,*variables,order='lex')==S.groebner(right,*variables,order='lex')
def intersect(left,right,variables):
    u=S.Dummy('u')
    basis=S.groebner([u*f for f in left]+[(1-u)*g for g in right],u,*variables,order='lex')
    return [p.as_expr() for p in basis.polys if not p.as_expr().has(u)]
def universal_chart():
    x,e,c,a,b,d,w=S.symbols('x e c A B C lambda')
    F,G,R,s,t=S.symbols('F G R s t');H=R-w*G;z=t-c*s
    matrix=S.Matrix([[H,a*F+d*G],[-G,H+b*F],[e*s,-z]])
    Q=S.expand(H*H+b*F*H+a*F*G+d*G*G)
    L1=z*G-e*s*(H+b*F);L2=z*H+e*s*(a*F+d*G)
    minors=[S.expand(matrix.extract(rows,[0,1]).det()) for rows in ((0,1),(0,2),(1,2))]
    require(all(S.expand(u-v)==0 for u,v in zip(minors,(Q,-L2,L1))),'all universal Hilbert--Burch minors')
    f=(x-c)**2+e**2*d;g=e*b*(x-c)-e**2*a;h=-e*a*(x-c)-e**2*b*d;r=w*g+h
    for expression in (Q,L1,L2):
        require(S.expand(expression.subs({F:f,G:g,R:r,s:1,t:x},simultaneous=True))==0,'universal graph substitution')
    equations=S.Poly(f-x*x,x).all_coeffs()+S.Poly(g,x).all_coeffs()+S.Poly(r,x).all_coeffs()
    require(same_ideal(equations,[c,e*a,e*b,e**2*d],(c,w,e,a,b,d)),'scheme fibre before taking radicals')
    disc=S.Matrix([[0,a/2,b/2],[a/2,d,0],[b/2,0,1]]).det()
    require(S.expand(disc+(a*a+d*b*b)/4)==0,'conic determinant')
    ell=S.symbols('ell')
    chi=lambda u,v:(u+1)*(v+1)*(v+2)/2
    polynomial=S.expand(chi(ell,ell)-2*chi(ell-1,ell-1)-chi(ell,ell-2)+2*chi(ell-1,ell-2))
    require(polynomial==3*ell+1,'bigraded resolution Hilbert polynomial')
    return {'minors':3,'graph_substitutions':3,'exact_fibre_ideal':'(c,eA,eB,e^2C)',
            'conic_determinant':'-(A^2+CB^2)/4','Hilbert_polynomial':str(polynomial),'all_pass':True}
def primary_and_adjacency():
    e,a,b,c,x,g,h=S.symbols('e A B C x G H')
    variables=(e,a,b,c);ideal=[e*a,e*b,e*e*c]
    primary=intersect(intersect([e],[a,b,c],variables),[a,b,e*e],variables)
    require(same_ideal(primary,ideal,variables),'irredundant primary intersection')
    require(same_ideal(intersect([e],[a,b,c],variables),[e*a,e*b,e*c],variables),'radical intersection')
    require(S.groebner(ideal,*variables).reduce((e*c)**2)[1]==0,'square-zero nilradical')
    require(S.groebner(ideal,*variables).reduce(e*c)[1]!=0,'nilradical is nonzero')
    # For monomial ideals I:m is generated by f/gcd(f,m) for the generators f.
    colon=[S.cancel(f/S.gcd(f,e*c)) for f in ideal]
    require(same_ideal(colon,[e,a,b],variables),'exact annihilator of the nilpotent generator')
    union=intersect([g,h],[x,h*h],(x,g,h))
    require(same_ideal(union,[x*g,x*h,h*h],(x,g,h)),'planar doubled-line union')
    u=S.symbols('u')
    require(same_ideal([x*g-e*h,x*h,h*h,u*e-1],
                       [x*x*g,h-u*x*g,u*e-1],(u,e,x,g,h)), 'jet family on reciprocal-slope chart')
    w0,w1=S.symbols('w0 w1')
    inv=S.series(1/(w0+w1*x),x,0,2).removeO()
    require(S.expand(inv-(1/w0-w1*x/w0**2))==0,'jet inversion transition')
    return {'primary_decomposition':['(e)','(A,B,C)','(A,B,e^2)'],
            'nilradical':'(eC)','annihilator':'(e,A,B)','double_line_union_verified':True,
            'reciprocal_jet_chart_verified':True,'inversion_transition_verified':True}
def partition_profiles():
    records=[]
    for r in range(8):
        for s in range(6):
            dims=[s+2*r+2*len(T) for k in range(r+1) for T in itertools.combinations(range(r),k)]
            require(len(dims)==2**r,'number of component choices')
            require(all(dims.count(s+2*r+2*k)==math.comb(r,k) for k in range(r+1)),'component dimensions and multiplicities')
            # Inclusion-exclusion on each two-component factor: 5+4-2.
            euler=(5+4-2)**r*2**s
            require(euler==7**r*2**s,'Euler characteristic product')
            records.append({'length_two_contacts':r,'length_one_contacts':s,'components':2**r,
                            'dimensions':sorted(set(dims)),'Euler_characteristic':euler,'nilpotence_order':r+1 if r else 1})
    return records
def gcd_tangent_tests():
    x=S.symbols('x');records=[]
    for a,parts in [(2,(1,)),(2,(2,)),(3,(1,1)),(3,(2,)),(3,(3,)),(4,(2,1)),(4,(2,2)),(5,(2,1)),(5,(3,2)),(6,(2,2,1))]:
        d=sum(parts);k=len(parts);degree=a-d
        roots=S.symbols('z:'+str(k));ff=S.symbols('f:'+str(degree));gg=S.symbols('g:'+str(degree))
        H=S.prod((x-roots[i])**m for i,m in enumerate(parts))
        f1=x**degree+sum(ff[j]*x**j for j in range(degree))
        g1=sum(gg[j]*x**j for j in range(degree))
        f=S.Poly(S.expand(H*f1),x);g=S.Poly(S.expand(H*g1),x)
        params=list(roots)+list(ff)+list(gg)
        coordinates=[f.nth(j) for j in range(a)]+[g.nth(j) for j in range(a)]
        point={z:2+i for i,z in enumerate(roots)}
        point.update({v:1 if j==0 else 0 for j,v in enumerate(ff)})
        point.update({v:1 if j==0 else 0 for j,v in enumerate(gg)})
        rank=S.Matrix(coordinates).jacobian(params).subs(point).rank()
        require(rank==k+2*degree,'exact gcd-stratum tangent dimension')
        records.append({'a':a,'partition':parts,'coefficient_rank':rank,'including_w_dimension':rank+a,'codimension':2*d-k})
    return records

def main():
    ap=argparse.ArgumentParser();ap.add_argument('--skip-inherited',action='store_true');args=ap.parse_args()
    inherited=False
    if not args.skip_inherited:
        subprocess.run([sys.executable,str(HERE.parent/'v162/check_v162.py')],check=True)
        previous=HERE.parent/'v162/EXACT_CHECKS_V162.json'
        data=json.loads(previous.read_text())
        require(data['all_checks_pass'],'full inherited v162 chain')
        (HERE/'INHERITED_V162_CHECKS_RERUN.json').write_bytes(previous.read_bytes());inherited=True
    result={'revision':163,'universal_Hilbert_Burch_chart':universal_chart(),
            'primary_structure_and_adjacency':primary_and_adjacency(),
            'component_profiles':partition_profiles(),'gcd_stratum_tangent_tests':gcd_tangent_tests(),
            'inherited_v162_suite_rerun':inherited,'all_checks_pass':True,
            'general_proofs_certified_by_computation':False,
            'external_independent_proof_audit_claimed':False,
            'script_sha256':hashlib.sha256(Path(__file__).read_bytes()).hexdigest()}
    (HERE/'EXACT_CHECKS_V163.json').write_text(json.dumps(result,indent=2)+'\n')
    print('All v163 exact audits passed; these are checks of equations, not general proof certificates.',flush=True)
if __name__=='__main__':main()
