#!/usr/bin/env python3
"""Materialize the eleven Round-Seventeen controlling manuscripts.

The script is deterministic and fail-closed: registered sources are copied
byte-for-byte, every expected Round-Sixteen referee report must exist, and each
paper main file is regenerated from its existing preamble plus the one active
Round-Seventeen module.
"""
from __future__ import annotations

from pathlib import Path
import hashlib
import json
import re

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "revision" / "round17-referee-final"

PAPERS = {
    "A1-exact-benchmarks": {
        "code": "A1",
        "source": "A1_GLOBAL_HYBRID_CONORMAL_FCLT.tex",
        "platform": "A1-HYBRID-CONORMAL-v17",
        "abstract": r"""We construct a single finite-dimensional autonomous hybrid Hamiltonian
realization of the driven baker benchmark and separate it from its symbolic
natural extension.  Parameter derivatives are defined on a fixed
Sobolev--conormal Hilbert scale carrying bulk, face, corner, and higher flag
currents.  A closed all-order chain rule yields explicit response words with
uniform remainder bounds.  A Hilbert-valued Gordin decomposition then gives a
Radon current-valued functional central limit theorem with trace-class
covariance.  Mechanical work and risk calibration remain distinct typed
claims.""",
    },
    "A2-sinai-homological-pressure": {
        "code": "A2",
        "source": "A2_MATRIX_COEFFICIENT_RAW_LLT.tex",
        "platform": "SINAI-INDUCED-RAW-LLT-v17",
        "abstract": r"""For a compact finite-horizon Sinai family we construct one induced
parent-fold Banach bundle carrying homology, return count, and physical roof.
Lattice rank and returned temporal non-integrability are proved on explicit
regular branch families.  High vertical frequencies are controlled directly
by branchwise physical integration by parts on matrix coefficients; no flat
trace, nuclear trace, or Fredholm determinant is invoked.  Fourier inversion
therefore yields an unsmoothed four-dimensional vector--return--roof density
local limit theorem and the corresponding ratio conditioning.""",
    },
    "A3-full-empirical-path-ldp": {
        "code": "A3",
        "source": "A3_ENTROPY_CONTROLLED_STOPPED_LDP.tex",
        "platform": "SINAI-STOPPED-CONTROL-LDP-v17",
        "abstract": r"""We prove deterministic-clock empirical-path large-deviation principles
for collision and physical time by an entropy-control method on the legal
renewal edge shift.  The state records recurrent edge flow, singular
exposure, mesoscopic and recession profiles, and the pointed terminal
excursion.  Arbitrary predictable controls are handled by entropy relaxation,
not by assigning them the stationary spectral gap.  The full terminal branch
pays its full selection entropy; a prefix-only observation pays the exact
negative log probability of all legal completions.""",
    },
    "A4-history-memory-universal-pressure": {
        "code": "A4",
        "source": "A4_GLOBAL_HARRIS_FORCED_MEMORY.tex",
        "platform": "SINAI-GLOBAL-HARRIS-MEMORY-v17",
        "abstract": r"""The prepared Sinai future is generated by one unchanged past kernel.
A small-distance coupling, a Lyapunov drift, and a common small set produce a
patched weak-Harris metric and a weighted spectral gap.  A fixed multiplier
Banach algebra gives an analytic Feynman--Kac and eigenfunction-Doob tower.
The unsmoothed renewal resolvent is continued with integrable vertical bounds,
and a common-domain Schur complement yields the complete forced
Mori--Zwanzig equation, including the unresolved initial component.  The
martingale rough-path tangent is proved in the same history topology.""",
    },
    "B1-microcanonical-preparation": {
        "code": "B1",
        "source": "B1_DIRECT_CANONICAL_COEFFICIENT.tex",
        "platform": "HS-EXACT-N-COEFFICIENT-v17",
        "abstract": r"""We derive the source-dependent microcanonical denominator directly from
the positive interacting exact-particle-number hard-sphere integral.  No
independence of connected components and no probabilistic interpretation of
signed polymer activities are used.  Sequential physical-cell exposure and
velocity integration by parts give one integrable characteristic-function
majorant over all frequencies, a uniformly positive covariance, and a
geometric mixed-shell local coefficient theorem.  The proof order is
strictly grand-canonical B2, then B1 conditioning, then the microcanonical B2
large-deviation theorem.""",
    },
    "B2-collision-clusters-dynamic-ldp": {
        "code": "B2",
        "source": "B2_GLOBAL_PRECONTACT_POSITIVE_RECOVERY.tex",
        "platform": "HS-PRECONTACT-POSITIVE-LDP-v17",
        "abstract": r"""Actual hard-sphere contacts are represented by a compatible Green trace
and genuine open pre-contact evaluation maps.  A surplus collision is imposed
as a zero-set constraint; reflection and the later hard-sphere future are
introduced only on that zero set.  Genealogywise coarea bounds are summed by a
fixed-horizon factorial majorant.  The lower bound uses conservative smoothing
and positive Maxwellian mixing to approximate every finite-action balanced
pair inside the positive collision cone.  This gives the grand-canonical and,
after exact-number conditioning, microcanonical joint density--contact LDPs.""",
    },
    "B3-hamilton-boltzmann-cotangents": {
        "code": "B3",
        "source": "B3_CUMULANT_MOSCO_PROCESS.tex",
        "platform": "HS-JOINT-GAUSSIAN-MOSCO-v17",
        "abstract": r"""We prove a finite-time hypocoercive observability estimate and closed
range for the linearized balance operator.  Exact localized finite-volume
cumulants then yield a tight joint density--contact Gaussian process on a
nuclear dual space.  The collision random measure uses control $qA_f$ and
integrand $\Delta p+\psi$, so the biased intensity is counted once.  An
independent exactly balanced quadratic recovery establishes Mosco convergence
and twice epi-differentiability of the action on the Cameron--Martin domain
$\operatorname{Ran}\Sigma^{1/2}$.""",
    },
    "B4-nonlinear-kinetic-semigroups": {
        "code": "B4",
        "source": "B4_CONTROL_TRANSFER_TROTTER_KATO.tex",
        "platform": "HS-NISIO-TROTTER-KATO-v17",
        "abstract": r"""We distinguish the deterministic flow, Koopman observables, probability
laws, factorial hierarchies, and limiting kinetic values.  The dynamic
entropy action has compact sublevels and defines a strongly continuous Nisio
semigroup.  Its discounted variational resolvent satisfies the nonlinear
resolvent identity, has full range, and generates an m-dissipative graph with
comparison.  State-dependent controls are transferred by their relative
multiplier rather than by reusing one collision measure.  A single diagonal
BBGKY graph-core corrector verifies all nonlinear Trotter--Kato hypotheses.""",
    },
    "C1-information-risk-sensitive-saddles": {
        "code": "C1",
        "source": "C1_REGULAR_FILTER_QMD.tex",
        "platform": "FILTER-DOMINATED-QMD-v17",
        "abstract": r"""Weak convergence of joint laws does not make disintegration continuous.
We therefore keep a global weak belief state but prove Feller filtering on
model-derived dominated Sobolev charts that control unnormalized kernels and
their observation derivatives.  Atomic microscopic observations enter by an
exponentially good regularization.  The unnormalized positive kernel, its
evidence, and its projective zero-evidence direction form an exact Markov
belief state with measurable dynamic programming.  Tolerance-dependent
bounded-Lipschitz coordinates approximate the full value, and the exact
regular experiment is QMD, LAN, and locally Bernstein--von Mises.""",
    },
    "C2-cotangent-rigidity-tangent-representations": {
        "code": "C2",
        "source": "C2_ACCRETIVE_FORM_FUNCTOR.tex",
        "platform": "TYPED-STRICT-FORM-RESPONSE-v17",
        "abstract": r"""We separate weighted strict Radon duality, strong spectral response, and
closed form realizations.  All varying Hilbert spaces are transported to a
fixed reference space and the metric connection is included in every
response derivative.  Dissipativity makes the finite-dimensional compressed
resolvent strictly accretive in the right half-plane; resolved vectors outside
the generator domain are handled by a form-level Schur complement.  We prove
model-specific pressure-functional rigidity, changing-filtration optional
projection convergence, and a category whose typed contractions preserve
rates, covariances, cotangents, and memory.""",
    },
    "D1-deterministic-theta-contractions": {
        "code": "D1",
        "source": "D1_LATENT_PHASE_SEMIGROUP.tex",
        "platform": "LATENT-PHASE-POSTERIOR-v17",
        "abstract": r"""A phase is introduced as a genuine positive latent variable with
conditional microscopic path laws.  The joint labelled experiment has a good
large-deviation principle and contracts to the minimum of the phase costs and
component rates.  Restricted pressures use one consistent sign and the exact
finite-volume value is a log-sum-exp.  Dynamic consistency is restored by
carrying the adapted phase posterior in the state; the marginal log-sum alone
is not called a semigroup.  Quantitative complex dominance gives phase-local
response charts, and second-order component weights determine labelled
Gaussian mixtures at coexistence.""",
    },
}

LABEL_MAP = {
    "A1": [
        ["thm:r17-a1-conormal", "thm:r17-a1-fclt"],
        ["thm:r17-a1-conormal", "thm:r17-a1-response"],
        ["thm:r17-a1-fclt"],
        ["thm:r17-a1-global", "prop:r17-a1-work"],
    ],
    "A2": [
        ["thm:r17-a2-bundle", "lem:r17-a2-ibp"],
        ["thm:r17-a2-bundle"],
        ["lem:r17-a2-ibp", "thm:r17-a2-fourier"],
        ["thm:r17-a2-fourier", "thm:r17-a2-llt"],
        ["thm:r17-a2-bundle", "lem:r17-a2-arithmetic", "lem:r17-a2-uni"],
    ],
    "A3": [
        ["thm:r17-a3-entropy", "thm:r17-a3-relax"],
        ["lem:r17-a3-terminal", "thm:r17-a3-collision", "thm:r17-a3-physical"],
        ["prop:r17-a3-space", "thm:r17-a3-tight"],
        ["thm:r17-a3-relax", "thm:r17-a3-collision"],
        ["thm:r17-a3-main"],
    ],
    "A4": [
        ["lem:r17-a4-coupling", "thm:r17-a4-harris"],
        ["thm:r17-a4-harris"],
        ["lem:r17-a4-coupling", "lem:r17-a4-drift", "thm:r17-a4-harris"],
        ["thm:r17-a4-fk", "thm:r17-a4-renewal"],
        ["lem:r17-a4-compression", "thm:r17-a4-memory"],
        ["thm:r17-a4-main"],
    ],
    "B1": [
        ["lem:r17-b1-cell", "thm:r17-b1-fourier"],
        ["lem:r17-b1-cell"],
        ["thm:r17-b1-fourier"],
        ["lem:r17-b1-saddle", "thm:r17-b1-coefficient"],
        ["thm:r17-b1-transfer"],
    ],
    "B2": [
        ["lem:r17-b2-precontact", "lem:r17-b2-gain", "thm:r17-b2-majorant"],
        ["thm:r17-b2-density"],
        ["thm:r17-b2-density", "thm:r17-b2-exposure"],
        ["thm:r17-b2-gc"],
        ["thm:r17-b2-mc"],
    ],
    "B3": [
        ["lem:r17-b3-cumulants", "thm:r17-b3-clt"],
        ["thm:r17-b3-mosco"],
        ["thm:r17-b3-observability"],
        ["lem:r17-b3-cumulants", "thm:r17-b3-clt"],
        ["thm:r17-b3-mosco"],
        ["thm:r17-b3-main"],
    ],
    "B4": [
        ["lem:r17-b4-transfer", "thm:r17-b4-nisio"],
        ["lem:r17-b4-compact"],
        ["thm:r17-b4-nisio", "thm:r17-b4-comparison"],
        ["thm:r17-b4-corrector"],
        ["thm:r17-b4-limit"],
        ["thm:r17-b4-intertwiner"],
        ["thm:r17-b4-main"],
    ],
    "C1": [
        ["thm:r17-c1-chart"],
        ["thm:r17-c1-chart", "thm:r17-c1-stability"],
        ["thm:r17-c1-chart"],
        ["thm:r17-c1-dpp"],
        ["thm:r17-c1-lan"],
        ["thm:r17-c1-main"],
    ],
    "C2": [
        ["thm:r17-c2-memory"],
        ["thm:r17-c2-connection"],
        ["thm:r17-c2-dual"],
        ["thm:r17-c2-rigidity"],
        ["thm:r17-c2-optional"],
        ["thm:r17-c2-connection", "thm:r17-c2-memory"],
        ["thm:r17-c2-functor"],
    ],
    "D1": [
        ["thm:r17-d1-joint"],
        ["thm:r17-d1-joint"],
        ["thm:r17-d1-semigroup"],
        ["thm:r17-d1-charts"],
        ["thm:r17-d1-semigroup"],
        ["thm:r17-d1-gaussian"],
        ["thm:r17-d1-contraction"],
    ],
}

REPORT_RE = re.compile(r"^###\s+(\d+)\.\s+(.+)$", re.M)


def report_objections(paper: Path) -> list[dict[str, str]]:
    report = paper / "REFEREE_REPORT_ROUND16_GPT56_PRO.md"
    if not report.is_file():
        raise SystemExit(f"missing Round-Sixteen report: {report}")
    return [{"number": n, "title": title.strip()} for n, title in REPORT_RE.findall(report.read_text(encoding="utf-8"))]


def write_author_response(paper: Path, meta: dict[str, str]) -> None:
    objections = report_objections(paper)
    mappings = LABEL_MAP[meta["code"]]
    if len(objections) != len(mappings):
        raise SystemExit(f"objection/mapping mismatch for {paper.name}: {len(objections)} != {len(mappings)}")
    lines = [
        f"# {meta['code']} response to the Round-Sixteen referee report",
        "",
        "The Round-Sixteen candidate was recovered and audited but was not treated as an accepted proof.  The Round-Seventeen manuscript replaces every failed mechanism positively; no theorem is deleted or converted to a no-go statement.",
        "",
        "| # | Referee objection | Round-Seventeen proof labels |",
        "|---:|---|---|",
    ]
    for item, labels in zip(objections, mappings):
        rendered = ", ".join(f"`{x}`" for x in labels)
        title = item["title"].replace("|", "\\|")
        lines.append(f"| {item['number']} | {title} | {rendered} |")
    lines += [
        "",
        "The active `ROUND17_POSITIVE_CLOSURE.tex` is byte-identical to the registered source named in `ROUND17_MATERIALIZATION_MANIFEST.json`.  Build and structural checks are reproducibility gates, not substitutes for independent external mathematical review.",
        "",
    ]
    (paper / "AUTHOR_RESPONSE_ROUND17.md").write_text("\n".join(lines), encoding="utf-8")


def materialize(name: str, meta: dict[str, str]) -> dict[str, object]:
    paper = ROOT / "papers" / name
    main = paper / "main.tex"
    source = SRC / meta["source"]
    active = paper / "ROUND17_POSITIVE_CLOSURE.tex"
    if not main.is_file() or not source.is_file():
        raise SystemExit(f"missing source/main for {name}")
    text = source.read_text(encoding="utf-8")
    if any(ord(c) < 32 and c not in "\n\t" for c in text):
        raise SystemExit(f"ASCII control in {source}")
    active.write_bytes(source.read_bytes())
    write_author_response(paper, meta)

    old = main.read_text(encoding="utf-8")
    marker = r"\begin{document}"
    if marker not in old:
        raise SystemExit(f"missing document marker in {main}")
    preamble = old.split(marker, 1)[0].rstrip()
    new = (
        preamble + "\n" + marker + "\n\\raggedbottom\n"
        + "\\begin{abstract}\n" + meta["abstract"].strip() + "\n\\end{abstract}\n"
        + "\\maketitle\n"
        + "\\noindent\\textbf{Platform identifier:} \\texttt{" + meta["platform"] + "}.\\par\n"
        + "\\noindent\\textbf{Controlling revision:} \\texttt{ROUND17-REFEREE-POSITIVE-CLOSURE}.\\par\n"
        + "\\noindent\\textbf{Registered proof source:} \\texttt{" + meta["source"].replace("_", r"\_") + "}.\\par\n"
        + "\\tableofcontents\n\n"
        + "\\input{ROUND17_POSITIVE_CLOSURE.tex}\n\n"
        + "\\section*{Scope and verification status}\n"
        + "This manuscript states a positive theorem reconstruction in the model-specific regular regime declared in its controlling theorems.  Cross-paper inputs follow the Round-Seventeen dependency ledger.  Repository source identity, proof-structure, counterexample, and build checks are internal reproducibility gates and do not replace independent external mathematical review.\n"
        + "\\printbibliography\n\\end{document}\n"
    )
    main.write_text(new, encoding="utf-8")
    data = source.read_bytes()
    return {
        "folder": f"papers/{name}",
        "code": meta["code"],
        "registered_source": f"revision/round17-referee-final/{meta['source']}",
        "active_module": f"papers/{name}/ROUND17_POSITIVE_CLOSURE.tex",
        "source_bytes": len(data),
        "source_sha256": hashlib.sha256(data).hexdigest(),
        "objections": len(report_objections(paper)),
    }


manifest = [materialize(name, meta) for name, meta in PAPERS.items()]
(ROOT / "ROUND17_MATERIALIZATION_MANIFEST.json").write_text(
    json.dumps({
        "schema": "theta-theory-round17-materialization-v1",
        "review_tree": "d3833aaa2db4bf0a13a67083f27ff23f28ab6e4f",
        "paper_count": len(manifest),
        "referee_objections": sum(x["objections"] for x in manifest),
        "papers": manifest,
    }, indent=2, sort_keys=True) + "\n",
    encoding="utf-8",
)
print(f"ROUND17_MATERIALIZED {len(manifest)}/11 objections={sum(x['objections'] for x in manifest)}")
