#!/usr/bin/env python3
"""Fail-closed structural verification for the round-eight revision."""
from __future__ import annotations

from pathlib import Path
import hashlib
import json
import re
import sys

ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / "ROUND8_MATERIALIZATION_MANIFEST.json"
HEADER = "% Generated by tools/materialize_round8_referee.py; do not hand-edit.\n"

ENV_RE = re.compile(r"\\begin\{(?:theorem|lemma|proposition|corollary)\}")
PROOF_RE = re.compile(r"\\begin\{proof\}")
LABEL_RE = re.compile(r"\\label\{([^}]+)\}")
REF_RE = re.compile(r"\\(?:ref|eqref|cref|Cref)\{([^}]+)\}")
CONTROL_RE = re.compile(r"[\x00-\x08\x0b\x0c\x0e-\x1f]")

DAG = {
    "A1-exact-benchmarks": [],
    "A2-sinai-homological-pressure": [],
    "A3-full-empirical-path-ldp": ["A2-sinai-homological-pressure"],
    "A4-history-memory-universal-pressure": [
        "A2-sinai-homological-pressure",
        "A3-full-empirical-path-ldp",
    ],
    "B1-microcanonical-preparation": [],
    "B2-collision-clusters-dynamic-ldp": ["B1-microcanonical-preparation"],
    "B3-hamilton-boltzmann-cotangents": [
        "B1-microcanonical-preparation",
        "B2-collision-clusters-dynamic-ldp",
    ],
    "B4-nonlinear-kinetic-semigroups": [
        "B2-collision-clusters-dynamic-ldp",
        "B3-hamilton-boltzmann-cotangents",
    ],
    "C1-information-risk-sensitive-saddles": [
        "B1-microcanonical-preparation",
        "B2-collision-clusters-dynamic-ldp",
        "B3-hamilton-boltzmann-cotangents",
        "B4-nonlinear-kinetic-semigroups",
    ],
    "C2-cotangent-rigidity-tangent-representations": [
        "A4-history-memory-universal-pressure",
        "B3-hamilton-boltzmann-cotangents",
        "B4-nonlinear-kinetic-semigroups",
    ],
    "D1-deterministic-theta-contractions": [
        "A2-sinai-homological-pressure",
        "B1-microcanonical-preparation",
        "B2-collision-clusters-dynamic-ldp",
        "C1-information-risk-sensitive-saddles",
    ],
}

REQUIRED = {
    "A1-exact-benchmarks": [
        "complete dynamic germ surface",
        "q=s_{i-1}+p_i s_j",
        "depth-weighted current scale",
        "Symplectic routing",
        "Autonomous routed suspension",
    ],
    "A2-sinai-homological-pressure": [
        "renormalized physical current bundle",
        "Finite parameter-uniform certificate family",
        "Dispersing two-branch derivative",
        "Correctly scaled vector--roof LLT",
        "G_n n^{-1/2}",
    ],
    "A3-full-empirical-path-ldp": [
        "actual profile",
        "marked edge-flow state",
        "Projective epigraph LDP",
        "Actual-excursion recession recovery",
        "terminal cut excursion",
    ],
    "A4-history-memory-universal-pressure": [
        "\\mathcal F^-_0",
        "Nondegenerate past disintegration",
        "\\mathcal H_{\\rm res}\\oplus Z",
        "zI-A-\\widehat C(z)^{-1}",
        "Uniform quenched rough invariance principle",
    ],
    "B1-microcanonical-preparation": [
        "Linearly many smooth blocks",
        "Ce^{-c\\mu}",
        "Typical-sector covariance",
        "\\mu^{-1}\\operatorname{Cov}_\\lambda(C_{\\rm tot})",
        "Exact finite-saddle coefficient",
    ],
    "B2-collision-clusters-dynamic-ldp": [
        "Closed kinetic trace and Green identity",
        "Positive boundary-renewal semigroup",
        "Dispersing monotonicity",
        "Depth-independent first-surplus Gramian",
        "One-block graph-domain estimate",
        "Commuting path-law smoothing",
    ],
    "B3-hamilton-boltzmann-cotangents": [
        "may have either sign",
        "KKT curvature cancellation",
        "Positive cumulant limit",
        "Coercive Schur completion",
        "Tree-decaying cumulant density",
    ],
    "B4-nonlinear-kinetic-semigroups": [
        "Dynamic-only transition action",
        "Exact cocycle of dynamic cost",
        "Smooth bounded graph core",
        "Finite graph-domain Poisson corrector",
        "two-scale slope-capped penalty",
        "R\\to\\infty",
    ],
    "C1-information-risk-sensitive-saddles": [
        "stratified current tower",
        "Evidence-lifted Bayes updates",
        "no uniform positive",
        "Uniform coarea local-limit ratio",
        "strategy-reachable beliefs",
    ],
    "C2-cotangent-rigidity-tangent-representations": [
        "\\overline{\\operatorname{span}}",
        "uniform Cesaro Lyapunov",
        "Kato parallel transport",
        "need not be mutually absolutely continuous",
        "zP_\\eta-A_\\eta-C_\\eta(z)^{-1}",
        "\\mathcal C^\\sharp",
    ],
    "D1-deterministic-theta-contractions": [
        "Phase-restricted partition functions",
        "No such neighborhood is asserted across a coexistence point",
        "Lee--Yang",
        "microscopic mixture theorem",
        "generally false formula",
        "Phase-stratified thin-shell conditioning",
    ],
}

FORBIDDEN = {
    "A1-exact-benchmarks": ["finite biseam complex is a bijective"],
    "A2-sinai-homological-pressure": [],
    "A3-full-empirical-path-ldp": ["the Gamma limit exists by definition"],
    "A4-history-memory-universal-pressure": [
        "\\widehat K(z)=\\widehat C(z)^{-1}-zI-A",
        "stable-leaf quotient history",
    ],
    "B1-microcanonical-preparation": ["fixed $n_0$-particle sector supplies the uniform covariance"],
    "B2-collision-clusters-dynamic-ldp": ["symplectic frame-reset construction"],
    "B3-hamilton-boltzmann-cotangents": ["the raw perspective Hessian is coercive"],
    "B4-nonlinear-kinetic-semigroups": [
        "entire cutoff equal one on a box",
        "\\eta^{-1}\\omega(\\eta d)",
    ],
    "C1-information-risk-sensitive-saddles": ["uniformly bounded normalized posterior current"],
    "C2-cotangent-rigidity-tangent-representations": [
        "\\frac{d\\nu_\\eta}{d\\nu_0}",
        "\\widehat K=C^{-1}-zP-A",
    ],
    "D1-deterministic-theta-contractions": [
        "one nonvanishing finite MGF across coexistence",
        "follows by conjugating the maximum pressure",
    ],
}


def sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def check_dag() -> None:
    visiting: set[str] = set()
    visited: set[str] = set()

    def dfs(node: str) -> None:
        if node in visiting:
            raise ValueError(f"dependency cycle at {node}")
        if node in visited:
            return
        visiting.add(node)
        for parent in DAG[node]:
            if parent not in DAG:
                raise ValueError(f"unknown dependency {parent} for {node}")
            dfs(parent)
        visiting.remove(node)
        visited.add(node)

    for node in DAG:
        dfs(node)


def main() -> None:
    if not MANIFEST.is_file():
        raise SystemExit("ROUND8 materialization manifest missing")
    manifest = json.loads(MANIFEST.read_text(encoding="utf-8"))
    errors: list[str] = []
    results: dict[str, object] = {}
    total_env = total_proofs = 0

    if set(manifest["papers"]) != set(DAG):
        errors.append("manifest paper registry differs from dependency registry")

    try:
        check_dag()
    except ValueError as exc:
        errors.append(str(exc))

    for paper, meta in manifest["papers"].items():
        source_path = ROOT / meta["source"]
        module_path = ROOT / meta["module"]
        main_path = ROOT / meta["main"]
        report_path = ROOT / meta["report"]
        response_path = ROOT / meta["response"]
        for path, kind in [
            (source_path, "source"),
            (module_path, "module"),
            (main_path, "main"),
            (report_path, "round-seven report"),
            (response_path, "round-eight response"),
        ]:
            if not path.is_file():
                errors.append(f"{paper}: missing {kind}: {path}")
        if not source_path.is_file() or not module_path.is_file() or not main_path.is_file():
            continue

        source_bytes = source_path.read_bytes()
        module_bytes = module_path.read_bytes()
        source_text = source_bytes.decode("utf-8")
        module_text = module_bytes.decode("utf-8")
        main_text = main_path.read_text(encoding="utf-8")

        if CONTROL_RE.search(source_text) or CONTROL_RE.search(module_text):
            errors.append(f"{paper}: ASCII control byte remains")
        if module_text != HEADER + source_text:
            errors.append(f"{paper}: registered source and active module are not byte-identical")
        if meta["source_sha256"] != sha256(source_bytes):
            errors.append(f"{paper}: manifest source SHA mismatch")
        if r"\input{ROUND8_POSITIVE_CLOSURE.tex}" not in main_text:
            errors.append(f"{paper}: main does not load round eight")
        if re.search(r"\\input\{ROUND[0-7]_POSITIVE_CLOSURE\.tex\}", main_text):
            errors.append(f"{paper}: main still loads an older controlling module")
        if "ROUND8-REFEREE-POSITIVE-CLOSURE" not in main_text:
            errors.append(f"{paper}: round-eight controlling marker absent")

        env = len(ENV_RE.findall(module_text))
        proofs = len(PROOF_RE.findall(module_text))
        total_env += env
        total_proofs += proofs
        if env != proofs:
            errors.append(f"{paper}: theorem/proof mismatch {env}/{proofs}")

        labels = LABEL_RE.findall(module_text)
        refs = REF_RE.findall(module_text)
        duplicate = sorted({x for x in labels if labels.count(x) > 1})
        missing = sorted({x for x in refs if x not in set(labels)})
        if duplicate:
            errors.append(f"{paper}: duplicate labels {duplicate}")
        if missing:
            errors.append(f"{paper}: unresolved local references {missing}")

        flat_module = re.sub(r"\s+", " ", module_text).lower()
        for token in REQUIRED[paper]:
            flat_token = re.sub(r"\s+", " ", token).lower()
            if flat_token not in flat_module:
                errors.append(f"{paper}: required mechanism absent: {token}")
        for token in FORBIDDEN[paper]:
            if token in module_text:
                errors.append(f"{paper}: forbidden failed mechanism remains: {token}")

        response_text = response_path.read_text(encoding="utf-8") if response_path.is_file() else ""
        if "no theorem is replaced by a no-go statement" not in response_text:
            errors.append(f"{paper}: positive-disposition response marker absent")

        results[paper] = {
            "status": "PASS",
            "source_bytes": len(source_bytes),
            "source_sha256": sha256(source_bytes),
            "module_bytes": len(module_bytes),
            "module_sha256": sha256(module_bytes),
            "theorem_like_environments": env,
            "proofs": proofs,
            "labels": len(labels),
            "references": len(refs),
        }

    output = {
        "schema": "theta-theory-round8-structural-verification-v1",
        "status": "PASS" if not errors else "FAIL",
        "paper_count": len(manifest["papers"]),
        "dependency_dag": "PASS" if not any("dependency" in e for e in errors) else "FAIL",
        "total_theorem_like_environments": total_env,
        "total_proofs": total_proofs,
        "papers": results,
        "errors": errors,
    }
    (ROOT / "ROUND8_STRUCTURAL_VERIFICATION.json").write_text(
        json.dumps(output, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    if errors:
        for error in errors:
            print(f"ROUND8_VERIFY_ERROR {error}", file=sys.stderr)
        raise SystemExit(1)
    print(
        f"ROUND8_STRUCTURAL_VERIFICATION_PASS papers={len(results)} "
        f"theorem_proof={total_env}/{total_proofs}"
    )


if __name__ == "__main__":
    main()
