"""Read-only source verification and actual regressions/build for Round 53.

The manifest is an input, never regenerated by this verifier. Output receipts
are written only under artifacts/round53 (excluded from source identities).
Finite execution and TeX compilation are not mathematical proof checking.
"""
from __future__ import annotations
import argparse
import hashlib
import json
from pathlib import Path
import re
import shutil
import subprocess
import sys

ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/'artifacts/round53'


def digest(path):
    data=path.read_bytes()
    return {'sha256':hashlib.sha256(data).hexdigest(),
            'git_blob':hashlib.sha1(b'blob '+str(len(data)).encode()+b'\0'+data).hexdigest()}


def run(argv,name):
    result=subprocess.run(argv,cwd=ROOT,text=True,stdout=subprocess.PIPE,stderr=subprocess.STDOUT)
    (OUT/name).write_text(result.stdout)
    if result.returncode:
        raise RuntimeError(f'{argv[0]} failed ({result.returncode}); see {name}')


def main():
    parser=argparse.ArgumentParser()
    parser.add_argument('--pdf',action='store_true',help='Require three actual pdflatex passes')
    args=parser.parse_args()
    OUT.mkdir(parents=True,exist_ok=True)
    manifest=json.loads((ROOT/'round53/SOURCE_MANIFEST.json').read_text())
    for name,expected in manifest['files'].items():
        if digest(ROOT/name)!=expected:
            raise RuntimeError(f'Source identity mismatch: {name}')
    seen=set()
    def visit(name):
        if name in seen:
            return
        if name not in manifest['files']:
            raise RuntimeError(f'Unmanifested TeX input: {name}')
        seen.add(name)
        text=(ROOT/name).read_text()
        for child in re.findall(r'\\(?:input|include)\{([^}]+)\}',text):
            visit(child if child.endswith('.tex') else child+'.tex')
    visit('ROUND53_REVISION.tex')
    for round_ in (51,53):
        run([sys.executable,f'tests/test_round{round_}.py','--json-out',
             f'artifacts/round53/ROUND{round_}_REGRESSION.json'],f'round{round_}-tests.log')
    build={'executed':False}
    if args.pdf:
        if not shutil.which('pdflatex'):
            raise RuntimeError('pdflatex is required by --pdf')
        for pass_ in (1,2,3):
            run(['pdflatex','-interaction=nonstopmode','-halt-on-error',
                 '-output-directory=artifacts/round53','ROUND53_REVISION.tex'],f'latex-pass{pass_}.txt')
        log=(OUT/'ROUND53_REVISION.log').read_text()
        if re.search(r'Overfull \\[hv]box|(?:Reference|Citation).*undefined|There were undefined',log):
            raise RuntimeError('Unresolved reference/citation or overfull box in final TeX log')
        build={'executed':True,'passes':3,'pdf_sha256':digest(OUT/'ROUND53_REVISION.pdf')['sha256'],
               'undefined_references':False,'overfull_boxes':False}
    receipts=[json.loads((OUT/f'ROUND{r}_REGRESSION.json').read_text()) for r in (51,53)]
    result={'review_base':manifest['review_base'],'verified_sources':len(manifest['files']),
            'tex_dependency_closure':sorted(seen),'tests_run':sum(x['tests_run'] for x in receipts),
            'failures':sum(x['failures'] for x in receipts),'errors':sum(x['errors'] for x in receipts),
            'all_tests_passed':all(x['success'] for x in receipts),'build':build,
            'scope':'Exact source identities, finite execution and optional TeX build; not a formal proof'}
    (OUT/'VERIFICATION.json').write_text(json.dumps(result,indent=2)+'\n')
    print(json.dumps(result,indent=2))

if __name__=='__main__':
    main()
