#!/usr/bin/env python3
from __future__ import annotations
import argparse,gzip,hashlib,json
from collections import Counter
from pathlib import Path
ROOT=Path(__file__).resolve().parent;P="cm2_round306c21a_source_g_1008_r204_A1_A2_direct_feature_kernel";L=P+"_ledger.jsonl.gz";R=P+"_result.json";R204="cm2_round204_source_g_wall_return_signature_local_replacement_certificate.json";C20="cm2_round306c20a_source_g_126468_preserved_direct_box_support_kernel_ledger.jsonl.gz";PINS={R204:"e7e1c49bebcb8c01f0fb4b33af66e4f2a8de560f121cae65f4971b2fec3e1818",C20:"bab9dcb7482d439b937c151823926c7339cafcd62edc7816c523126c20b4e922"};EXPECTED={"A1_R204_TARGET_SHEET":224,"A2_R204_SOURCE_TARGET_CURVE":504,"A2_R204_SOURCE_TARGET_ENDPOINT":280};EXISTENCE={"PINNED_ROUND182_FULL_2D_ENDPOINT_BRACKET":192,"ROUND204_TAIL_T_BRACKET_MONOTONICITY_AND_P_OUTER_INTERVAL_NEWTON":32}
class E(RuntimeError):pass
def need(v,l):
 if type(v)is not bool or not v:raise E(l)
def c(v):return json.dumps(v,sort_keys=True,separators=(",",":"),ensure_ascii=True,allow_nan=False).encode("ascii")
def h(v):return hashlib.sha256(c(v)).hexdigest()
def fh(q):
 x=hashlib.sha256()
 with q.open("rb")as f:
  while b:=f.read(1048576):x.update(b)
 return x.hexdigest()
def rows(q):
 with gzip.open(q,"rb")as f:
  for line in f:
   raw=line[:-1];r=json.loads(raw);need(line.endswith(b"\n") and c(r)==raw,"canonical");b=dict(r);need(b.pop("row_sha256",None)==h(b),"closure");yield r
def closed(r,l):b=dict(r);need(b.pop("row_sha256",None)==h(b),l)
def build(q):
 for n,x in PINS.items():need(fh(ROOT/n)==x,"pin:"+n)
 owner_rows=[r for r in rows(ROOT/C20)if r["fine_family"]=="ROUND204_REGION"];owner={r["member_id"]:r for r in owner_rows};need(len(owner_rows)==len(owner)==736,"owner census");d=json.loads((ROOT/R204).read_bytes());sheets={};out=[];counts=Counter();existence=Counter();sheet_refs=set();curve_refs=set()
 for s in d["result"]["formal_2D_sheet_lineage"]["target_sheet_rows"]:
  closed(s,"sheet");oid=s["half_open_owner_region_row_id"];sid=s["half_open_shadow_region_row_id"];need(s["sheet_row_id"]not in sheets and oid in owner and sid in owner,"sheet identity");need(s["ambient_dimension"]==2 and s["sheet_kind"]=="TARGET_REGULAR_GRAPH_SHEET_CELL" and s["target_factor_graph_axis"]=="t" and s["target_t_derivative_sign"]=="STRICT_POSITIVE" and s["existence_certification"]in EXISTENCE,"sheet authority");need(s["local_dimension_lineage_materialized"]is True and s["lower_dimensional_credit"]==s["global_exact_key_disposition_credit"]==s["whole_original_tube_credit"]==0,"sheet boundary");box=[*s["leaf_t_exact_bounds"],*s["base_p_s_exact_bounds"]];need(owner[oid]["support_ast"]["coordinate_chart"]==s["chart"]==owner[sid]["support_ast"]["coordinate_chart"] and owner[oid]["support_ast"]["bounds"]==box==owner[sid]["support_ast"]["bounds"],"sheet support join");theorem={"kind":"A1_UNIQUE_TARGET_REGULAR_GRAPH_SHEET","coordinate_chart":s["chart"],"target_factor":s["owner_target"],"base_coordinates":["p","s"],"exact_base_rectangle":s["base_p_s_exact_bounds"],"graph_coordinate":"t","leaf_t_bounds":s["leaf_t_exact_bounds"],"implicit_equation":"TARGET_FACTOR_MINUS_INTEGER_WALL_EQUALS_ZERO","integer_wall":s["integer_wall"],"wall_axis":s["wall_axis"],"strict_t_derivative_sign":s["target_t_derivative_sign"],"existence_certificate":s["existence_certification"],"analytic_lineage":{"origin_row_id":s["origin_row_id"],"leaf_row_id":s["leaf_row_id"],"source_t0_sheet_row_id":s["source_t0_sheet_row_id"]},"unique_graph_point_per_base_point":True};body={"schema":"cm2.round306c21a.source-g-1008-r204-A1-A2-direct-feature-kernel.v1.row.v1","feature_ordinal":len(out),"obligation_kind":"A1_R204_TARGET_SHEET","feature_row_id":s["sheet_row_id"],"owner_member_id":oid,"shadow_member_id":sid,"owner_fresh_component_id":owner[oid]["fresh_component_id"],"shadow_fresh_component_id":owner[sid]["fresh_component_id"],"feature_theorem_ast":theorem,"feature_theorem_ast_sha256":h(theorem),"source_row_sha256":s["row_sha256"],"formal_credit":{"A1":1,"A2":0},"strict_nonpromotion":{"DSU_edge":0,"DSU_union":0,"B1A":0,"B2":0,"maximality":0,"CM2":0}};out.append({**body,"row_sha256":h(body)});sheets[s["sheet_row_id"]]=s;counts["A1_R204_TARGET_SHEET"]+=1;existence[s["existence_certification"]]+=1
 curves={}
 for r in d["result"]["formal_1D_boundary_and_intersection_lineage"]["rows"]:
  if not r["geometry_kind"].startswith("TARGET_GRAPH_"):continue
  closed(r,"curve");refs=sorted(set(r["incident_sheet_row_ids"])&set(sheets),key=lambda x:x.encode());need(r["edge_row_id"]not in curves and r["ambient_dimension"]==1 and refs==sorted(r["incident_sheet_row_ids"],key=lambda x:x.encode()) and r["half_open_owner_region_row_id"] in owner,"curve incidence");need(r["local_dimension_lineage_materialized"]is True and r["lower_dimensional_credit"]==r["global_exact_key_disposition_credit"]==r["whole_original_tube_credit"]==0,"curve boundary");sheet_refs.update(refs);theorem={"kind":"A2_EXACT_TARGET_GRAPH_CURVE_INCIDENCE","ambient_dimension":1,"geometry_kind":r["geometry_kind"],"geometry_key":r["geometry_key"],"incident_A1_sheet_row_ids":refs,"endpoint_row_ids":r["endpoint_0D_row_ids"],"half_open_owner_sheet_row_id":r["half_open_owner_sheet_row_id"],"half_open_shadow_sheet_row_ids":r["half_open_shadow_sheet_row_ids"],"half_open_owner_policy":r["half_open_owner_policy"],"exact_source_target_intersection":r["exact_source_target_intersection"]};body={"schema":"cm2.round306c21a.source-g-1008-r204-A1-A2-direct-feature-kernel.v1.row.v1","feature_ordinal":len(out),"obligation_kind":"A2_R204_SOURCE_TARGET_CURVE","feature_row_id":r["edge_row_id"],"owner_member_id":r["half_open_owner_region_row_id"],"owner_fresh_component_id":owner[r["half_open_owner_region_row_id"]]["fresh_component_id"],"feature_theorem_ast":theorem,"feature_theorem_ast_sha256":h(theorem),"source_row_sha256":r["row_sha256"],"formal_credit":{"A1":0,"A2":1},"strict_nonpromotion":{"DSU_edge":0,"DSU_union":0,"B1A":0,"B2":0,"maximality":0,"CM2":0}};out.append({**body,"row_sha256":h(body)});curves[r["edge_row_id"]]=r;counts["A2_R204_SOURCE_TARGET_CURVE"]+=1
 for r in d["result"]["formal_0D_endpoint_and_corner_lineage"]["rows"]:
  if r["geometry_kind"]!="TARGET_GRAPH_P_S_POINT":continue
  closed(r,"point");refs=sorted(set(r["incident_1D_row_ids"])&set(curves),key=lambda x:x.encode());sheet_ids=sorted(set(r["incident_2D_sheet_row_ids"])&set(sheets),key=lambda x:x.encode());need(r["ambient_dimension"]==0 and refs and sheet_ids and r["half_open_owner_region_row_id"] in owner,"point incidence");need(r["local_dimension_lineage_materialized"]is True and r["lower_dimensional_credit"]==r["global_exact_key_disposition_credit"]==r["whole_original_tube_credit"]==0,"point boundary");curve_refs.update(refs);theorem={"kind":"A2_EXACT_TARGET_GRAPH_ENDPOINT_INCIDENCE","ambient_dimension":0,"geometry_kind":r["geometry_kind"],"geometry_key":r["geometry_key"],"incident_A2_curve_row_ids":refs,"incident_A1_sheet_row_ids":sheet_ids,"half_open_owner_1D_row_id":r["half_open_owner_1D_row_id"],"half_open_shadow_1D_row_ids":r["half_open_shadow_1D_row_ids"],"half_open_owner_policy":r["half_open_owner_policy"],"exact_source_target_intersection_endpoint":r["exact_source_target_intersection_endpoint"]};body={"schema":"cm2.round306c21a.source-g-1008-r204-A1-A2-direct-feature-kernel.v1.row.v1","feature_ordinal":len(out),"obligation_kind":"A2_R204_SOURCE_TARGET_ENDPOINT","feature_row_id":r["point_row_id"],"owner_member_id":r["half_open_owner_region_row_id"],"owner_fresh_component_id":owner[r["half_open_owner_region_row_id"]]["fresh_component_id"],"feature_theorem_ast":theorem,"feature_theorem_ast_sha256":h(theorem),"source_row_sha256":r["row_sha256"],"formal_credit":{"A1":0,"A2":1},"strict_nonpromotion":{"DSU_edge":0,"DSU_union":0,"B1A":0,"B2":0,"maximality":0,"CM2":0}};out.append({**body,"row_sha256":h(body)});counts["A2_R204_SOURCE_TARGET_ENDPOINT"]+=1
 need(counts==Counter(EXPECTED)and existence==Counter(EXISTENCE)and sheet_refs==set(sheets)and curve_refs==set(curves)and len(out)==1008,"feature census/exhaustion");out.sort(key=lambda r:(r["obligation_kind"].encode(),r["feature_row_id"].encode()));out=[{**{k:v for k,v in r.items()if k not in{"feature_ordinal","row_sha256"}},"feature_ordinal":i}for i,r in enumerate(out)];out=[{**r,"row_sha256":h(r)}for r in out]
 q.mkdir(parents=True,exist_ok=True);raw=b"".join(c(x)+b"\n"for x in out)
 with(q/L).open("wb")as f:
  with gzip.GzipFile(filename="",mode="wb",fileobj=f,mtime=0)as g:g.write(raw)
 desc={"filename":L,"row_count":1008,"size":(q/L).stat().st_size,"sha256":fh(q/L)};body={"schema":"cm2.round306c21a.source-g-1008-r204-A1-A2-direct-feature-kernel.v1","status":"PASS_1008_R204_A1_A2_DIRECT_FEATURE_THEOREMS","feature_census":EXPECTED,"A1_existence_census":EXISTENCE,"A1_strict_t_derivative_sign_census":{"STRICT_POSITIVE":224},"incidence_exhaustion":{"all_224_A1_sheets_referenced_by_A2_curves":True,"all_504_A2_curves_referenced_by_A2_endpoints":True},"A1_credit":224,"A2_credit":784,"total_A1_A2_credit":1008,"remaining_preserved_A1_A2_obligation_debt":79084,"input_pins":[{"filename":n,"sha256":x}for n,x in sorted(PINS.items())],"ledger":desc,"strict_nonpromotion":{"new_DSU_edges":0,"new_DSU_unions":0,"B1A":0,"B2":0,"maximality":0,"CM2":"NO-GO_FOR_CLAIM"}};z={**body,"result_sha256":h(body)};(q/R).write_bytes(c(z));return z
def main():
 p=argparse.ArgumentParser();p.add_argument("--candidate-dir",required=True);a=p.parse_args();z=build(Path(a.candidate_dir).resolve());print(c({"status":z["status"],"result_sha256":z["result_sha256"]}).decode());return 0
if __name__=="__main__":raise SystemExit(main())
