#!/usr/bin/env python3
from __future__ import annotations
import argparse,gzip,hashlib,json,sys
from collections import Counter,defaultdict
from fractions import Fraction as Q
from math import isqrt
from pathlib import Path
from flint import arb,ctx
ROOT=Path(__file__).resolve().parent;P="cm2_round306c21c_source_g_79084_r211_A1_A2_incidence_closure";L=P+"_ledger.jsonl.gz";R=P+"_result.json";R173="cm2_round173_source_g_exact_return_signature_transport_certificate.json";R208="cm2_round208_source_g_outgoing_direct_signature_materialization_certificate.json";R211="cm2_round211_source_g_outgoing_half_open_owner_materialization_certificate.json";C20="cm2_round306c20a_source_g_126468_preserved_direct_box_support_kernel_ledger.jsonl.gz";C21BL="cm2_round306c21b_source_g_17716_r211_self_contained_sheet_theorem_materialization_ledger.jsonl.gz";C21BR="cm2_round306c21b_source_g_17716_r211_self_contained_sheet_theorem_materialization_result.json";PINS={R173:"5ff82c5822f543109da0d50c0637d0d2f9148a738b1a21b16878c70e5505cf1a",R208:"4d01fb9cee639ec59786c078f7a20b3bbcd5c18ea674fabbfce64e250e765938",R211:"bb03a39a74a237b9f4449214c698795856fce4d6be2195c4f9d7774cd1d4183f",C20:"bab9dcb7482d439b937c151823926c7339cafcd62edc7816c523126c20b4e922",C21BL:"1500052cf49cfa7a22388567173a912be6b79d2ba647ad5d1906f9e170dc26bb",C21BR:"bcf5d1f2b04faca4b5e5b74e79ec0b21a7e91f4aa6ffa7fe23d3b5e13fdbc73a"};STRICT={"STRICT_NEGATIVE","STRICT_POSITIVE"}
class E(RuntimeError):pass
def need(v,l):
 if type(v)is not bool or not v:raise E(l)
def c(v):return json.dumps(v,sort_keys=True,separators=(",",":"),ensure_ascii=True,allow_nan=False).encode("ascii")
def h(v):return hashlib.sha256(c(v)).hexdigest()
def fh(q):
 x=hashlib.sha256()
 with q.open("rb")as f:
  while b:=f.read(1048576):x.update(b)
 return x.hexdigest()
def closed(r,l):b=dict(r);need(b.pop("row_sha256",None)==h(b),l)
def rows(q,verify=True):
 with gzip.open(q,"rb")as f:
  for line in f:
   need(line.endswith(b"\n"),"newline");raw=line[:-1];r=json.loads(raw)
   if verify:need(c(r)==raw,"canonical");closed(r,"row closure")
   yield r
def envelope(name):
 d=json.loads((ROOT/name).read_bytes());need(set(d)=={"schema","result","result_sha256"}and d["result_sha256"]==h(d["result"]),"envelope:"+name);return d["result"]
def aq(v):v=Q(v);return arb(v.numerator)/v.denominator
def hull(a,b):
 a,b=Q(a),Q(b);need(a<=b,"hull");m=(a+b)/2;r=(b-a)/2;return aq(m)+arb(0,aq(r).upper())
def sg(v):return"STRICT_POSITIVE"if bool(v>0)else"STRICT_NEGATIVE"if bool(v<0)else"OVERWRAP"
def plus(a,b):return a[0]+b[0],tuple(x+y for x,y in zip(a[1],b[1]))
def minus(a):return-a[0],tuple(-x for x in a[1])
def diff(a,b):return plus(a,minus(b))
def times(a,b):return a[0]*b[0],tuple(x*b[0]+a[0]*y for x,y in zip(a[1],b[1]))
def scaled(a,v):v=aq(v);return a[0]*v,tuple(x*v for x in a[1])
def quotient(a,b):return times(a,(1/b[0],tuple(-x/(b[0]*b[0])for x in b[1])))
def constant(v):return aq(v),(arb(0),arb(0),arb(0))
def root(a):v=a[0].sqrt();return v,tuple(x/(2*v)for x in a[1])
def target(v):need(v.startswith("W[")and v.endswith("]"),"target");a,b=v[2:-1].split(",");return int(a),int(b)
def factor_map(chart,lift,tv,pv,sv,sigma=None):
 t=(tv,(arb(1),arb(0),arb(0)));s=(sv,(arb(0),arb(0),arb(1)));one=constant(1)
 if sigma is None:p=(pv,(arb(0),arb(1),arb(0)));rp=root(diff(one,times(p,p)))
 else:u=(pv,(arb(0),arb(1),arb(0)));u2=times(u,u);den=plus(one,u2);p=scaled(quotient(diff(one,u2),den),sigma);rp=quotient(scaled(u,2),den)
 rt=root(diff(one,times(t,t)));cell=chart.split(":")[1];need(cell in{"E","W","N","S"},"chart")
 if cell=="E":nx,ny=rt,t
 elif cell=="W":nx,ny=minus(rt),t
 elif cell=="N":nx,ny=t,rt
 else:nx,ny=t,minus(rt)
 ux=diff(times(rp,nx),times(p,ny));uy=plus(times(rp,ny),times(p,nx));sx=scaled(nx,Q(9,25));sy=scaled(ny,Q(9,25));ix,iy=target(lift);cx=plus(constant(Q(ix)+Q(1,2)),s);cy=constant(Q(iy)+Q(1,2));dx=diff(cx,sx);dy=diff(cy,sy);trace=plus(minus(times(uy,dx)),times(ux,dy));radicand=diff(constant(Q(16,625)),times(trace,trace));need(bool(radicand[0]>0),"radicand");radius=root(radicand);ox=scaled(plus(minus(times(radius,ux)),times(trace,uy)),Q(25,4));oy=scaled(diff(minus(times(radius,uy)),times(trace,ux)),Q(25,4));return{"HPLUS":plus(ox,oy),"HMINUS":diff(ox,oy)}
def sqrt_cover(v,bits=192):
 v=Q(v);d=1<<bits;n=v.numerator<<(2*bits);r=isqrt(n//v.denominator)
 while r*r*v.denominator<n:r+=1
 while r and(r-1)*(r-1)*v.denominator>=n:r-=1
 z=Q(r,d);need(z*z>=v,"sqrt cover");return z
def face(box,side):v=box[0]if side=="LOWER"else box[1];return[v,v,*box[2:]]
def fixed(box,axis,upper):
 out=list(box);i={"t":0,"p":1,"s":2}[axis]*2;v=out[i+1]if upper else out[i];out[i]=out[i+1]=v;return out
def direct(chart,lift,box,factor):return factor_map(chart,lift,hull(box[0],box[1]),hull(box[2],box[3]),hull(box[4],box[5]))[factor]
def centered(chart,lift,box,factor):
 mids=[(Q(box[i])+Q(box[i+1]))/2 for i in(0,2,4)];point=[str(mids[0]),str(mids[0]),str(mids[1]),str(mids[1]),str(mids[2]),str(mids[2])];full=direct(chart,lift,box,factor);value=direct(chart,lift,point,factor)[0];env=[hull(box[0],box[1]),hull(box[2],box[3]),hull(box[4],box[5])];return value+sum((full[1][i]*(env[i]-aq(mids[i]))for i in range(3)),arb(0))
def curve_theorem(sheet,leaf,curve,owner,c21b):
 chart=owner["local_return_signature"]["source_chart"];lift=owner["local_return_signature"]["target_lift"];box=leaf["box"];factor=sheet["active_factor"];side=curve["face_side"];tq=Q(box[0]if side=="LOWER"else box[1]);endpoint=Q(box[2])==-1 or Q(box[3])==1;corners={};edges={}
 if not endpoint:
  mode="DIRECT_TPS";fb=face(box,side);full=direct(chart,lift,fb,factor);graph=full[1][1];axis="p";corner_specs={"SW":(fb[2],fb[4]),"SE":(fb[3],fb[4]),"NE":(fb[3],fb[5]),"NW":(fb[2],fb[5])}
  for label,(p,s)in corner_specs.items():
   value=direct(chart,lift,[str(tq),str(tq),p,p,s,s],factor)[0];corners[label]={"physical_TPS_point":[str(tq),p,s],"value_interval":str(value),"sign":sg(value)}
  specs={"S":(("SW","SE"),"s",False,1,"p"),"E":(("SE","NE"),"p",True,2,"s"),"N":(("NW","NE"),"s",True,1,"p"),"W":(("SW","NW"),"p",False,2,"s")}
  for edge,(pair,fix_axis,upper,index,tangent)in specs.items():
   eb=fixed(fb,fix_axis,upper);dual=direct(chart,lift,eb,factor);cv=centered(chart,lift,eb,factor);ds=sg(dual[0]);cs=sg(cv);selected=ds if ds in STRICT else cs;derivative=sg(dual[1][index]);ends=[corners[pair[0]]["sign"],corners[pair[1]]["sign"]]
   if selected in STRICT:need(ends==[selected,selected],"edge C0");disposition="STRICT_C0_ZERO_ABSENT"
   elif derivative in STRICT:disposition="UNIQUE_BRACKETED_ZERO"if set(ends)==STRICT else"STRICT_MONOTONE_ZERO_ABSENT"
   else:disposition="EDGE_ZERO_SET_UNRESOLVED"
   edges[edge]={"edge":edge,"proof_coordinate_system":"TPS","exact_closed_edge_box":eb,"tangent_coordinate":tangent,"endpoint_corner_labels":list(pair),"endpoint_corner_signs":ends,"direct_C0_interval":str(dual[0]),"direct_C0_sign":ds,"centered_C0_interval":str(cv),"centered_C0_sign":cs,"selected_C0_sign":selected,"tangent_derivative_interval":str(dual[1][index]),"tangent_derivative_sign":derivative,"disposition":disposition}
  proof_chart={"kind":"DIRECT_TPS","closed_face_box":fb}
 else:
  mode="STEREOGRAPHIC_TUS";left,right=Q(box[2]),Q(box[3]);sigma=-1 if left==-1 else 1;inner=right if sigma==-1 else left;u2=(1-sigma*inner)/(1+sigma*inner);u_max=aq(u2).sqrt();u_upper=sqrt_cover(u2);t=aq(tq);u_range=hull(0,u_upper);s_range=hull(box[4],box[5]);s_center=aq((Q(box[4])+Q(box[5]))/2);full=factor_map(chart,lift,t,u_range,s_range,sigma)[factor];graph=full[1][1];axis="u";corner_specs={"SW":(arb(0),aq(box[4]),str(Q(sigma)),box[4]),"SE":(u_max,aq(box[4]),str(inner),box[4]),"NE":(u_max,aq(box[5]),str(inner),box[5]),"NW":(arb(0),aq(box[5]),str(Q(sigma)),box[5])}
  for label,(u,s,p_exact,s_exact)in corner_specs.items():
   value=factor_map(chart,lift,t,u,s,sigma)[factor][0];corners[label]={"proof_TUS_point":[str(tq),("0"if label in{"SW","NW"}else"sqrt("+str(u2)+")"),s_exact],"physical_TPS_point":[str(tq),p_exact,s_exact],"value_interval":str(value),"sign":sg(value)}
  specs={"S":(("SW","SE"),u_range,aq(box[4]),u_max/2,aq(box[4]),1,"u"),"E":(("SE","NE"),u_max,s_range,u_max,s_center,2,"s"),"N":(("NW","NE"),u_range,aq(box[5]),u_max/2,aq(box[5]),1,"u"),"W":(("SW","NW"),arb(0),s_range,arb(0),s_center,2,"s")}
  for edge,(pair,u,s,uc,sc,index,tangent)in specs.items():
   dual=factor_map(chart,lift,t,u,s,sigma)[factor];point=factor_map(chart,lift,t,uc,sc,sigma)[factor][0];cv=point+dual[1][1]*(u-uc)+dual[1][2]*(s-sc);ds=sg(dual[0]);cs=sg(cv);selected=ds if ds in STRICT else cs;derivative=sg(dual[1][index]);ends=[corners[pair[0]]["sign"],corners[pair[1]]["sign"]]
   if selected in STRICT:need(ends==[selected,selected],"stereo edge C0");disposition="STRICT_C0_ZERO_ABSENT"
   elif derivative in STRICT:disposition="UNIQUE_BRACKETED_ZERO"if set(ends)==STRICT else"STRICT_MONOTONE_ZERO_ABSENT"
   else:disposition="EDGE_ZERO_SET_UNRESOLVED"
   edges[edge]={"edge":edge,"proof_coordinate_system":"TUS","tangent_coordinate":tangent,"endpoint_corner_labels":list(pair),"endpoint_corner_signs":ends,"direct_C0_interval":str(dual[0]),"direct_C0_sign":ds,"centered_C0_interval":str(cv),"centered_C0_sign":cs,"selected_C0_sign":selected,"tangent_derivative_interval":str(dual[1][index]),"tangent_derivative_sign":derivative,"disposition":disposition}
  proof_chart={"kind":"RATIONAL_STEREOGRAPHIC_TUS","sigma":sigma,"physical_p_endpoint":str(Q(sigma)),"physical_p_inner":str(inner),"exact_u_max_squared":str(u2),"interval_proof_u_upper_dyadic":str(u_upper),"closed_face_hull":[str(tq),str(tq),"0",str(u_upper),box[4],box[5]]}
 graph_sign=sg(graph);need(axis==curve["graph_axis"]and graph_sign in STRICT and all(v["sign"]in STRICT for v in corners.values()),"curve regularity");bracketed=sorted(edge for edge,evidence in edges.items()if evidence["disposition"]=="UNIQUE_BRACKETED_ZERO");need(all(evidence["disposition"]!="EDGE_ZERO_SET_UNRESOLVED"for evidence in edges.values())and"|".join(bracketed)==curve["boundary_edge_pair"],"edge exhaustion");theorem={"kind":"A2_UNIQUE_TWO_ENDPOINT_ACTIVE_FACTOR_BOUNDARY_CURVE","C21b_sheet_theorem_row_sha256":c21b["row_sha256"],"C21b_sheet_theorem_ast_sha256":c21b["theorem_ast_sha256"],"active_factor":factor,"face_side":side,"exact_t_face_coordinate":str(tq),"proof_chart":proof_chart,"graph_axis":axis,"graph_derivative_interval":str(graph),"graph_derivative_sign":graph_sign,"corner_evidence":corners,"edge_evidence":[edges[key]for key in sorted(edges)],"bracketed_boundary_edges":bracketed,"boundary_edge_pair":curve["boundary_edge_pair"],"each_boundary_endpoint_unique_by_strict_edge_derivative":True,"all_four_edges_exhaustively_resolved":True,"curve_regular_and_single_valued_in_selected_graph_axis":True,"inactive_factor_excludes_simultaneous_factor_zero":True};return theorem,edges,mode,graph_sign
def signature_core(v):return{k:x for k,x in v.items()if k not in{"outgoing_cell","target_chart"}}
def probe_sheet(sheet,leaf,owner,shadow):
 core=signature_core(owner["local_return_signature"]);need(core==signature_core(shadow["local_return_signature"]),"signature");cs=h(core);identity={"leaf_row_id":leaf["leaf_row_id"],"owner_region_row_id":owner["region_row_id"],"shadow_region_row_id":shadow["region_row_id"],"rule":"E_OR_W_OWNS__N_OR_S_SHADOWS"};pid="round209-half-open-sheet:"+h(identity);relation="HMINUS=2*Nx_ON_HPLUS_ZERO_SHEET"if sheet["active_factor"]=="HPLUS"else"HPLUS=2*Nx_ON_HMINUS_ZERO_SHEET";body={"sheet_row_id":pid,"leaf_row_id":leaf["leaf_row_id"],"origin_row_id":leaf["origin_row_id"],"occurrence_row_id":leaf["occurrence_row_id"],"retained_child_row_id":leaf["retained_child_row_id"],"leaf_classification":leaf["final_graph_classification"],"active_factor":sheet["active_factor"],"inactive_factor":sheet["inactive_factor"],"inactive_factor_whole_box_C0_proof":"DIRECT_WHOLE_BOX_C0","inactive_factor_whole_box_strict_sign":sheet["inactive_factor_whole_box_strict_sign"],"factor_identity_on_sheet":relation,"Nx_sign_on_sheet":sheet["inactive_factor_whole_box_strict_sign"],"owner_region_row_id":owner["region_row_id"],"shadow_region_row_id":shadow["region_row_id"],"owner_outgoing_cell":owner["outgoing_cell"],"shadow_outgoing_cell":shadow["outgoing_cell"],"owner_signature_core_sha256":cs,"shadow_signature_core_sha256":cs,"signature_difference_field_allowlist":["outgoing_cell","target_chart"],"Round173_half_open_rule":"E or W owns; N or S excludes","deterministic_unique_owner_lineage":True,"incidence_is_not_a_global_component":True,"formal_half_open_owner_credit":0,"whole_original_tube_credit":0,"global_exact_key_disposition_credit":0};return{**body,"row_sha256":h(body)}
def probe_curve(curve,sheet,leaf,owner,shadow):
 ps=probe_sheet(sheet,leaf,owner,shadow);identity={"sheet_row_id":ps["sheet_row_id"],"face_side":curve["face_side"],"boundary_edge_pair":curve["boundary_edge_pair"],"graph_axis":curve["graph_axis"],"provenance":curve["geometry_provenance"]};pid="round209-half-open-curve-incidence:"+h(identity);body={"curve_row_id":pid,"sheet_row_id":ps["sheet_row_id"],"sheet_row_sha256":ps["row_sha256"],"leaf_row_id":leaf["leaf_row_id"],"face_side":curve["face_side"],"graph_axis":curve["graph_axis"],"boundary_edge_pair":curve["boundary_edge_pair"],"geometry_provenance":curve["geometry_provenance"],"owner_region_row_id":owner["region_row_id"],"owner_outgoing_cell":owner["outgoing_cell"],"shadow_region_row_id":shadow["region_row_id"],"shadow_outgoing_cell":shadow["outgoing_cell"],"owner_signature_core_sha256":h(signature_core(owner["local_return_signature"])),"deterministic_owner_lineage_inherited_from_sheet":True,"incidence_is_not_a_global_component":True,"formal_half_open_owner_credit":0,"whole_original_tube_credit":0,"global_exact_key_disposition_credit":0};return{**body,"row_sha256":h(body)}
def probe_endpoint(endpoint,probe):
 identity={"curve_row_id":probe["curve_row_id"],"endpoint_ordinal":endpoint["endpoint_ordinal"],"boundary_edge":endpoint["boundary_edge"]};pid="round209-half-open-endpoint-incidence:"+h(identity);body={"endpoint_row_id":pid,"curve_row_id":probe["curve_row_id"],"curve_row_sha256":probe["row_sha256"],"sheet_row_id":probe["sheet_row_id"],"leaf_row_id":probe["leaf_row_id"],"face_side":probe["face_side"],"endpoint_ordinal":endpoint["endpoint_ordinal"],"boundary_edge":endpoint["boundary_edge"],"owner_region_row_id":probe["owner_region_row_id"],"owner_outgoing_cell":probe["owner_outgoing_cell"],"shadow_region_row_id":probe["shadow_region_row_id"],"shadow_outgoing_cell":probe["shadow_outgoing_cell"],"owner_signature_core_sha256":probe["owner_signature_core_sha256"],"deterministic_owner_lineage_inherited_from_curve":True,"incidence_is_not_a_global_component":True,"formal_half_open_owner_credit":0,"whole_original_tube_credit":0,"global_exact_key_disposition_credit":0};return{**body,"row_sha256":h(body)}
def c21b_index():
 out={}
 for row in rows(ROOT/C21BL,False):need(row["R211_sheet_row_id"]not in out,"C21b duplicate");out[row["R211_sheet_row_id"]]={"row_sha256":row["row_sha256"],"theorem_ast_sha256":row["theorem_ast_sha256"]}
 need(len(out)==17716,"C21b census");return out
def full_certificate(sheet,leaf,owner):
 chart=owner["local_return_signature"]["source_chart"];lift=owner["local_return_signature"]["target_lift"];need(not(Q(leaf["box"][2])==-1 or Q(leaf["box"][3])==1),"full stereo");faces=[]
 for side in("LOWER","UPPER"):
  stack=[(face(leaf["box"],side),0,0)];cells=[];overall=None
  while stack:
   box,dp,ds=stack.pop();dual=direct(chart,lift,box,sheet["active_factor"]);cv=centered(chart,lift,box,sheet["active_factor"]);direct_sign=sg(dual[0]);center_sign=sg(cv);selected=direct_sign if direct_sign in STRICT else center_sign
   if selected in STRICT:
    if overall is None:overall=selected
    need(selected==overall,"full face mixed");cells.append({"exact_closed_subbox":box,"direct_C0_interval":str(dual[0]),"direct_C0_sign":direct_sign,"centered_C0_interval":str(cv),"centered_C0_sign":center_sign,"selected_sign":selected});continue
   need(dp+ds<16,"full face depth");axis=1 if dp<=ds else 2;i=axis*2;mid=(Q(box[i])+Q(box[i+1]))/2;left=list(box);right=list(box);left[i+1]=str(mid);right[i]=str(mid);stack.append((right,dp+(axis==1),ds+(axis==2)));stack.append((left,dp+(axis==1),ds+(axis==2)))
  cells.sort(key=lambda row:c(row["exact_closed_subbox"]));faces.append({"face_side":side,"strict_active_factor_sign":overall,"subdivision_leaf_count":len(cells),"subdivision_certificate_rows":cells,"subdivision_certificate_rows_sha256":h(cells)})
 need({faces[0]["strict_active_factor_sign"],faces[1]["strict_active_factor_sign"]}==STRICT,"full bracket");return{"kind":"FULL_BASE_UNIQUE_GRAPH_BY_OPPOSITE_T_FACE_SIGNS_AND_C21B_STRICT_T_DERIVATIVE","face_certificates":faces,"opposite_face_signs":True}
def verify(q):
 ctx.prec=256
 for name,digest in PINS.items():need(fh(ROOT/name)==digest,"pin:"+name)
 raw=(q/R).read_bytes();result=json.loads(raw);need(c(result)==raw,"result canonical");body=dict(result);claimed=body.pop("result_sha256");need(claimed==h(body),"result closure");need(result["status"]=="PASS_ALL_79084_R211_A1_A2_OBLIGATIONS__PRESERVED_SEMANTIC_KERNEL_CLOSED"and(result["A1_credit"],result["A2_curve_credit"],result["A2_endpoint_credit"],result["total_A1_A2_credit"],result["remaining_preserved_A1_A2_obligation_debt"])==(17716,20456,40912,79084,0),"result census");need(result["PRESERVED_semantic_kernel_closed"]is True and(result["cumulative_member_support_credit"],result["remaining_global_member_support_debt"])==(182072,320132),"support boundary");need(result["curve_proof_chart_census"]=={"DIRECT_TPS":20200,"STEREOGRAPHIC_TUS":256}and result["curve_graph_derivative_sign_census"]=={"STRICT_NEGATIVE":10228,"STRICT_POSITIVE":10228}and result["curve_boundary_pair_census"]=={"E|N":3959,"E|S":3959,"N|S":4620,"N|W":3959,"S|W":3959},"curve census");need(result["curve_provenance_census"]=={"ROUND182_FULL_BASE_UNIQUE_GRAPH_FACE":3252,"ROUND186_ONE_ACTIVE_FACTOR_FULL_GRAPH":1104,"ROUND188_UNIQUE_TWO_ENDPOINT_FACTOR_CURVE":15844,"ROUND191_UNIQUE_TWO_ENDPOINT_STEREOGRAPHIC_FACTOR_CURVE":256}and result["sheet_classification_census"]=={"CLIPPED_2D_BOUNDARY_1D":17308,"FULL_2D":408}and result["full_sheet_subdivision_certificate_leaf_count"]==2820,"geometry census");need(result["input_pins"]==[{"filename":n,"sha256":x}for n,x in sorted(PINS.items())]and result["strict_nonpromotion"]=={"new_DSU_edges":0,"new_DSU_unions":0,"typed_global_support_ledger":0,"B1A":0,"B2":0,"maximality":0,"CM2":"NO-GO_FOR_CLAIM"},"nonpromotion");need(result["ledger"]["filename"]==L and result["ledger"]["row_count"]==79084 and result["ledger"]["size"]==(q/L).stat().st_size and result["ledger"]["sha256"]==fh(q/L),"ledger descriptor")
 r173=envelope(R173);need(r173["outgoing_chart_contract"]["diagonal_seam_rule"]=="E or W owns; N or S excludes","R173");r208=envelope(R208);r211=envelope(R211);c21br=json.loads((ROOT/C21BR).read_bytes());need(c21br["result_sha256"]=="d51822cd828c6911f931b5d7cc96061a9d349407b038c23b31e2924d0fbee51f","C21b result");c21b=c21b_index();leaves={row["leaf_row_id"]:row for row in r208["formal_leaf_geometry_ledger"]["rows"]};regions={row["region_row_id"]:row for row in r208["formal_local_open_3D_signature_ledger"]["rows"]};supports={row["member_id"]:row["fresh_component_id"]for row in rows(ROOT/C20)if row["fine_family"]=="ROUND208_REGION"};sheets={row["sheet_row_id"]:row for row in r211["formal_2D_sheet_owner_ledger"]["rows"]};curves=sorted(r211["formal_1D_curve_incidence_owner_ledger"]["rows"],key=lambda row:row["curve_row_id"].encode());curve_source={row["curve_row_id"]:row for row in curves};endpoints=sorted(r211["formal_0D_endpoint_incidence_owner_ledger"]["rows"],key=lambda row:row["endpoint_row_id"].encode());need(len(sheets)==17716 and len(curves)==20456 and len(endpoints)==40912,"source census");iterator=rows(q/L);pending_a1={};curve_meta={};probe_curves={};curves_by_sheet=defaultdict(list);mode_count=Counter();sign_count=Counter();pair_count=Counter();provenance=Counter()
 for sheet_id in sorted(sheets,key=lambda x:x.encode()):
  row=next(iterator,None);need(row is not None and row["obligation_kind"]=="A1_R211_OWNER_SHEET"and row["feature_row_id"]==sheet_id,"A1 order");pending_a1[sheet_id]=row
 for curve in curves:
  row=next(iterator,None);need(row is not None,"curve row");closed(curve,"R211 curve");sheet=sheets[curve["sheet_row_id"]];leaf=leaves[sheet["leaf_row_id"]];owner=regions[sheet["owner_region_row_id"]];shadow=regions[sheet["shadow_region_row_id"]];probe=probe_curve(curve,sheet,leaf,owner,shadow);need(curve["probe_curve_row_id"]==probe["curve_row_id"]and curve["probe_curve_row_sha256"]==probe["row_sha256"],"curve probe");theorem,edges,mode,graph_sign=curve_theorem(sheet,leaf,curve,owner,c21b[sheet["sheet_row_id"]]);row_body={"schema":"cm2.round306c21c.source-g-79084-r211-A1-A2-incidence-closure.v1.row.v1","obligation_kind":"A2_R211_OWNER_CURVE","feature_row_id":curve["curve_row_id"],"R211_sheet_row_id":sheet["sheet_row_id"],"owner_member_id":sheet["owner_region_row_id"],"owner_fresh_component_id":supports[sheet["owner_region_row_id"]],"theorem_ast":theorem,"theorem_ast_sha256":h(theorem),"source_bindings":{"reconstructed_R209_probe_curve_row_sha256":probe["row_sha256"],"R211_curve_owner_row_sha256":curve["row_sha256"],"C21b_sheet_theorem_row_sha256":c21b[sheet["sheet_row_id"]]["row_sha256"]},"formal_credit":{"A1":0,"A2":1},"strict_nonpromotion":{"DSU_edge":0,"DSU_union":0,"B1A":0,"B2":0,"maximality":0,"CM2":0}};expected={**row_body,"row_sha256":h(row_body)};need(row==expected,"independent curve reconstruction");curve_meta[curve["curve_row_id"]]={"row_sha256":row["row_sha256"],"theorem_ast_sha256":row["theorem_ast_sha256"],"edges":{edge:h(evidence)for edge,evidence in edges.items()}};probe_curves[curve["curve_row_id"]]=probe;curves_by_sheet[sheet["sheet_row_id"]].append(row["row_sha256"]);mode_count[mode]+=1;sign_count[graph_sign]+=1;pair_count[curve["boundary_edge_pair"]]+=1;provenance[curve["geometry_provenance"]]+=1
 for endpoint in endpoints:
  row=next(iterator,None);need(row is not None,"endpoint row");closed(endpoint,"R211 endpoint");curve=curve_source[endpoint["curve_row_id"]];sheet=sheets[curve["sheet_row_id"]];probe=probe_endpoint(endpoint,probe_curves[curve["curve_row_id"]]);need(endpoint["probe_endpoint_row_id"]==probe["endpoint_row_id"]and endpoint["probe_endpoint_row_sha256"]==probe["row_sha256"],"endpoint probe");meta=curve_meta[curve["curve_row_id"]];need(curve["boundary_edge_pair"].split("|")[endpoint["endpoint_ordinal"]-1]==endpoint["boundary_edge"],"endpoint incidence");theorem={"kind":"A2_UNIQUE_ALGEBRAIC_BOUNDARY_ENDPOINT","curve_theorem_row_sha256":meta["row_sha256"],"curve_theorem_ast_sha256":meta["theorem_ast_sha256"],"endpoint_ordinal":endpoint["endpoint_ordinal"],"boundary_edge":endpoint["boundary_edge"],"edge_evidence_sha256":meta["edges"][endpoint["boundary_edge"]],"endpoint_exists_and_is_unique":True,"uniqueness_authority":"STRICT_TANGENT_DERIVATIVE_PLUS_OPPOSITE_STRICT_CORNER_SIGNS"};row_body={"schema":"cm2.round306c21c.source-g-79084-r211-A1-A2-incidence-closure.v1.row.v1","obligation_kind":"A2_R211_OWNER_ENDPOINT","feature_row_id":endpoint["endpoint_row_id"],"R211_sheet_row_id":sheet["sheet_row_id"],"R211_curve_row_id":curve["curve_row_id"],"owner_member_id":sheet["owner_region_row_id"],"owner_fresh_component_id":supports[sheet["owner_region_row_id"]],"theorem_ast":theorem,"theorem_ast_sha256":h(theorem),"source_bindings":{"reconstructed_R209_probe_endpoint_row_sha256":probe["row_sha256"],"R211_endpoint_owner_row_sha256":endpoint["row_sha256"],"C21c_curve_theorem_row_sha256":meta["row_sha256"]},"formal_credit":{"A1":0,"A2":1},"strict_nonpromotion":{"DSU_edge":0,"DSU_union":0,"B1A":0,"B2":0,"maximality":0,"CM2":0}};expected={**row_body,"row_sha256":h(row_body)};need(row==expected,"independent endpoint reconstruction")
 need(next(iterator,None)is None,"ledger exhaustion");class_count=Counter();full_cells=0
 for sheet_id in sorted(sheets,key=lambda x:x.encode()):
  row=pending_a1[sheet_id];sheet=sheets[sheet_id];closed(sheet,"R211 sheet");leaf=leaves[sheet["leaf_row_id"]];owner=regions[sheet["owner_region_row_id"]];incident=curves_by_sheet[sheet_id];need(len(incident)==leaf["one_dimensional_clipping_curve_segment_count"],"A1 curve census")
  if leaf["final_graph_classification"]=="FULL_2D":need(not incident,"full incidence");existence=full_certificate(sheet,leaf,owner);full_cells+=sum(face_row["subdivision_leaf_count"]for face_row in existence["face_certificates"])
  else:need(leaf["final_graph_classification"]=="CLIPPED_2D_BOUNDARY_1D"and bool(incident),"clipped incidence");existence={"kind":"CLIPPED_REGULAR_SHEET_WITH_EXHAUSTIVE_VERIFIED_T_FACE_BOUNDARY_CURVES","verified_boundary_curve_row_sha256s":incident,"boundary_curve_count":len(incident),"endpoint_count":2*len(incident),"C21b_strict_t_derivative_plus_A2_boundary_curves_implies_nonempty_regular_sheet":True}
  theorem={"kind":"A1_R211_REGULAR_ACTIVE_FACTOR_ZERO_SHEET_DISCHARGE","C21b_sheet_theorem_row_sha256":c21b[sheet_id]["row_sha256"],"C21b_sheet_theorem_ast_sha256":c21b[sheet_id]["theorem_ast_sha256"],"leaf_classification":leaf["final_graph_classification"],"existence_and_boundary_closure":existence,"all_R211_curve_obligations_exhausted":True,"all_incident_curve_endpoints_exhausted":True};row_body={"schema":"cm2.round306c21c.source-g-79084-r211-A1-A2-incidence-closure.v1.row.v1","obligation_kind":"A1_R211_OWNER_SHEET","feature_row_id":sheet_id,"owner_member_id":sheet["owner_region_row_id"],"owner_fresh_component_id":supports[sheet["owner_region_row_id"]],"theorem_ast":theorem,"theorem_ast_sha256":h(theorem),"source_bindings":{"R211_sheet_owner_row_sha256":sheet["row_sha256"],"C21b_sheet_theorem_row_sha256":c21b[sheet_id]["row_sha256"]},"formal_credit":{"A1":1,"A2":0},"strict_nonpromotion":{"DSU_edge":0,"DSU_union":0,"B1A":0,"B2":0,"maximality":0,"CM2":0}};expected={**row_body,"row_sha256":h(row_body)};need(row==expected,"independent A1 reconstruction");class_count[leaf["final_graph_classification"]]+=1
 need(mode_count==result["curve_proof_chart_census"]and sign_count==result["curve_graph_derivative_sign_census"]and pair_count==result["curve_boundary_pair_census"]and provenance==result["curve_provenance_census"]and class_count==result["sheet_classification_census"]and full_cells==result["full_sheet_subdivision_certificate_leaf_count"],"replay census");return{"status":"PASS_INDEPENDENT_C21C_79084_R211_A1_A2_RECONSTRUCTION__PRESERVED_KERNEL_CLOSED_WITHOUT_PROMOTION","result_sha256":claimed,"A1_rows":17716,"A2_curve_rows":20456,"A2_endpoint_rows":40912,"full_sheet_subdivision_certificate_leaf_count":full_cells}
def main():
 need(sys.flags.isolated==1 and sys.dont_write_bytecode is True,"flags");p=argparse.ArgumentParser();p.add_argument("--candidate-dir");a=p.parse_args();q=ROOT if a.candidate_dir is None else Path(a.candidate_dir).resolve();print(c(verify(q)).decode());return 0
if __name__=="__main__":raise SystemExit(main())
