#!/usr/bin/env python3
from __future__ import annotations
import argparse,gzip,hashlib,json,sys
from collections import Counter
from pathlib import Path
ROOT=Path(__file__).resolve().parent;P="cm2_round306c21a_source_g_1008_r204_A1_A2_direct_feature_kernel";L=P+"_ledger.jsonl.gz";R=P+"_result.json";R204="cm2_round204_source_g_wall_return_signature_local_replacement_certificate.json";C20="cm2_round306c20a_source_g_126468_preserved_direct_box_support_kernel_ledger.jsonl.gz";PINS={R204:"e7e1c49bebcb8c01f0fb4b33af66e4f2a8de560f121cae65f4971b2fec3e1818",C20:"bab9dcb7482d439b937c151823926c7339cafcd62edc7816c523126c20b4e922"};EXPECTED={"A1_R204_TARGET_SHEET":224,"A2_R204_SOURCE_TARGET_CURVE":504,"A2_R204_SOURCE_TARGET_ENDPOINT":280};EXISTENCE={"PINNED_ROUND182_FULL_2D_ENDPOINT_BRACKET":192,"ROUND204_TAIL_T_BRACKET_MONOTONICITY_AND_P_OUTER_INTERVAL_NEWTON":32};NON={"DSU_edge":0,"DSU_union":0,"B1A":0,"B2":0,"maximality":0,"CM2":0}
class E(RuntimeError):pass
def need(v,l):
 if type(v)is not bool or not v:raise E(l)
def c(v):return json.dumps(v,sort_keys=True,separators=(",",":"),ensure_ascii=True,allow_nan=False).encode("ascii")
def h(v):return hashlib.sha256(c(v)).hexdigest()
def fh(q):
 x=hashlib.sha256()
 with q.open("rb")as f:
  while b:=f.read(1048576):x.update(b)
 return x.hexdigest()
def rows(q):
 with gzip.open(q,"rb")as f:
  for line in f:
   need(line.endswith(b"\n"),"newline");raw=line[:-1];r=json.loads(raw);need(c(r)==raw,"canonical");b=dict(r);need(b.pop("row_sha256",None)==h(b),"row closure");yield r
def closed(r,l):b=dict(r);need(b.pop("row_sha256",None)==h(b),l)
def rebuild():
 for n,x in PINS.items():need(fh(ROOT/n)==x,"pin:"+n)
 owner_rows=[r for r in rows(ROOT/C20)if r["fine_family"]=="ROUND204_REGION"];owner={r["member_id"]:r for r in owner_rows};need(len(owner_rows)==len(owner)==736,"owners");d=json.loads((ROOT/R204).read_bytes());sheets={};curves={};expected=[];counts=Counter();existence=Counter();sheet_refs=set();curve_refs=set()
 for source in d["result"]["formal_2D_sheet_lineage"]["target_sheet_rows"]:
  closed(source,"sheet closure");owner_id=source["half_open_owner_region_row_id"];shadow_id=source["half_open_shadow_region_row_id"];need(source["sheet_row_id"]not in sheets and owner_id in owner and shadow_id in owner,"sheet ids");need(source["ambient_dimension"]==2 and source["sheet_kind"]=="TARGET_REGULAR_GRAPH_SHEET_CELL" and source["target_factor_graph_axis"]=="t" and source["target_t_derivative_sign"]=="STRICT_POSITIVE" and source["existence_certification"]in EXISTENCE,"sheet theorem authority");need(source["local_dimension_lineage_materialized"]is True and source["lower_dimensional_credit"]==source["global_exact_key_disposition_credit"]==source["whole_original_tube_credit"]==0,"sheet strict boundary");support_box=[*source["leaf_t_exact_bounds"],*source["base_p_s_exact_bounds"]];need(owner[owner_id]["support_ast"]["coordinate_chart"]==source["chart"]==owner[shadow_id]["support_ast"]["coordinate_chart"] and owner[owner_id]["support_ast"]["bounds"]==support_box==owner[shadow_id]["support_ast"]["bounds"],"sheet support");theorem={"kind":"A1_UNIQUE_TARGET_REGULAR_GRAPH_SHEET","coordinate_chart":source["chart"],"target_factor":source["owner_target"],"base_coordinates":["p","s"],"exact_base_rectangle":source["base_p_s_exact_bounds"],"graph_coordinate":"t","leaf_t_bounds":source["leaf_t_exact_bounds"],"implicit_equation":"TARGET_FACTOR_MINUS_INTEGER_WALL_EQUALS_ZERO","integer_wall":source["integer_wall"],"wall_axis":source["wall_axis"],"strict_t_derivative_sign":source["target_t_derivative_sign"],"existence_certificate":source["existence_certification"],"analytic_lineage":{"origin_row_id":source["origin_row_id"],"leaf_row_id":source["leaf_row_id"],"source_t0_sheet_row_id":source["source_t0_sheet_row_id"]},"unique_graph_point_per_base_point":True};body={"schema":"cm2.round306c21a.source-g-1008-r204-A1-A2-direct-feature-kernel.v1.row.v1","feature_ordinal":0,"obligation_kind":"A1_R204_TARGET_SHEET","feature_row_id":source["sheet_row_id"],"owner_member_id":owner_id,"shadow_member_id":shadow_id,"owner_fresh_component_id":owner[owner_id]["fresh_component_id"],"shadow_fresh_component_id":owner[shadow_id]["fresh_component_id"],"feature_theorem_ast":theorem,"feature_theorem_ast_sha256":h(theorem),"source_row_sha256":source["row_sha256"],"formal_credit":{"A1":1,"A2":0},"strict_nonpromotion":NON};expected.append(body);sheets[source["sheet_row_id"]]=source;counts["A1_R204_TARGET_SHEET"]+=1;existence[source["existence_certification"]]+=1
 for source in d["result"]["formal_1D_boundary_and_intersection_lineage"]["rows"]:
  if not source["geometry_kind"].startswith("TARGET_GRAPH_"):continue
  closed(source,"curve closure");refs=sorted(set(source["incident_sheet_row_ids"])&set(sheets),key=lambda x:x.encode());need(source["edge_row_id"]not in curves and source["ambient_dimension"]==1 and refs==sorted(source["incident_sheet_row_ids"],key=lambda x:x.encode()) and source["half_open_owner_region_row_id"]in owner,"curve incidence");need(source["local_dimension_lineage_materialized"]is True and source["lower_dimensional_credit"]==source["global_exact_key_disposition_credit"]==source["whole_original_tube_credit"]==0,"curve strict boundary");sheet_refs.update(refs);theorem={"kind":"A2_EXACT_TARGET_GRAPH_CURVE_INCIDENCE","ambient_dimension":1,"geometry_kind":source["geometry_kind"],"geometry_key":source["geometry_key"],"incident_A1_sheet_row_ids":refs,"endpoint_row_ids":source["endpoint_0D_row_ids"],"half_open_owner_sheet_row_id":source["half_open_owner_sheet_row_id"],"half_open_shadow_sheet_row_ids":source["half_open_shadow_sheet_row_ids"],"half_open_owner_policy":source["half_open_owner_policy"],"exact_source_target_intersection":source["exact_source_target_intersection"]};owner_id=source["half_open_owner_region_row_id"];expected.append({"schema":"cm2.round306c21a.source-g-1008-r204-A1-A2-direct-feature-kernel.v1.row.v1","feature_ordinal":0,"obligation_kind":"A2_R204_SOURCE_TARGET_CURVE","feature_row_id":source["edge_row_id"],"owner_member_id":owner_id,"owner_fresh_component_id":owner[owner_id]["fresh_component_id"],"feature_theorem_ast":theorem,"feature_theorem_ast_sha256":h(theorem),"source_row_sha256":source["row_sha256"],"formal_credit":{"A1":0,"A2":1},"strict_nonpromotion":NON});curves[source["edge_row_id"]]=source;counts["A2_R204_SOURCE_TARGET_CURVE"]+=1
 for source in d["result"]["formal_0D_endpoint_and_corner_lineage"]["rows"]:
  if source["geometry_kind"]!="TARGET_GRAPH_P_S_POINT":continue
  closed(source,"point closure");refs=sorted(set(source["incident_1D_row_ids"])&set(curves),key=lambda x:x.encode());sheet_ids=sorted(set(source["incident_2D_sheet_row_ids"])&set(sheets),key=lambda x:x.encode());owner_id=source["half_open_owner_region_row_id"];need(source["ambient_dimension"]==0 and refs and sheet_ids and owner_id in owner,"point incidence");need(source["local_dimension_lineage_materialized"]is True and source["lower_dimensional_credit"]==source["global_exact_key_disposition_credit"]==source["whole_original_tube_credit"]==0,"point strict boundary");curve_refs.update(refs);theorem={"kind":"A2_EXACT_TARGET_GRAPH_ENDPOINT_INCIDENCE","ambient_dimension":0,"geometry_kind":source["geometry_kind"],"geometry_key":source["geometry_key"],"incident_A2_curve_row_ids":refs,"incident_A1_sheet_row_ids":sheet_ids,"half_open_owner_1D_row_id":source["half_open_owner_1D_row_id"],"half_open_shadow_1D_row_ids":source["half_open_shadow_1D_row_ids"],"half_open_owner_policy":source["half_open_owner_policy"],"exact_source_target_intersection_endpoint":source["exact_source_target_intersection_endpoint"]};expected.append({"schema":"cm2.round306c21a.source-g-1008-r204-A1-A2-direct-feature-kernel.v1.row.v1","feature_ordinal":0,"obligation_kind":"A2_R204_SOURCE_TARGET_ENDPOINT","feature_row_id":source["point_row_id"],"owner_member_id":owner_id,"owner_fresh_component_id":owner[owner_id]["fresh_component_id"],"feature_theorem_ast":theorem,"feature_theorem_ast_sha256":h(theorem),"source_row_sha256":source["row_sha256"],"formal_credit":{"A1":0,"A2":1},"strict_nonpromotion":NON});counts["A2_R204_SOURCE_TARGET_ENDPOINT"]+=1
 need(counts==Counter(EXPECTED)and existence==Counter(EXISTENCE)and sheet_refs==set(sheets)and curve_refs==set(curves)and len(expected)==1008,"source exhaustion");expected.sort(key=lambda r:(r["obligation_kind"].encode(),r["feature_row_id"].encode()));out=[]
 for ordinal,row in enumerate(expected):
  body={**row,"feature_ordinal":ordinal};out.append({**body,"row_sha256":h(body)})
 return out
def verify(q):
 raw=(q/R).read_bytes();z=json.loads(raw);need(c(z)==raw,"result canonical");body=dict(z);claimed=body.pop("result_sha256");need(claimed==h(body),"result closure");need(z["status"]=="PASS_1008_R204_A1_A2_DIRECT_FEATURE_THEOREMS"and z["feature_census"]==EXPECTED and z["A1_existence_census"]==EXISTENCE and z["A1_strict_t_derivative_sign_census"]=={"STRICT_POSITIVE":224},"result theorem census");need(z["incidence_exhaustion"]=={"all_224_A1_sheets_referenced_by_A2_curves":True,"all_504_A2_curves_referenced_by_A2_endpoints":True},"result incidence");need((z["A1_credit"],z["A2_credit"],z["total_A1_A2_credit"],z["remaining_preserved_A1_A2_obligation_debt"],z["ledger"]["row_count"])==(224,784,1008,79084,1008),"result credit");need(z["input_pins"]==[{"filename":n,"sha256":x}for n,x in sorted(PINS.items())]and z["strict_nonpromotion"]=={"new_DSU_edges":0,"new_DSU_unions":0,"B1A":0,"B2":0,"maximality":0,"CM2":"NO-GO_FOR_CLAIM"},"result boundary");need(fh(q/L)==z["ledger"]["sha256"]and(q/L).stat().st_size==z["ledger"]["size"],"descriptor");expected=rebuild();actual=list(rows(q/L));need(actual==expected,"independent row reconstruction");return{"status":"PASS_INDEPENDENT_C21A_1008_R204_A1_A2_FEATURE_THEOREMS","result_sha256":claimed,"rows":len(actual)}
def main():
 need(sys.flags.isolated==1 and sys.dont_write_bytecode is True,"flags");p=argparse.ArgumentParser();p.add_argument("--candidate-dir");a=p.parse_args();q=ROOT if a.candidate_dir is None else Path(a.candidate_dir).resolve();print(c(verify(q)).decode());return 0
if __name__=="__main__":raise SystemExit(main())
