#!/usr/bin/env python3
from __future__ import annotations
import argparse,gzip,hashlib,json,sys
from collections import Counter,defaultdict
from pathlib import Path
from typing import Any,Iterator

ROOT=Path(__file__).resolve().parent
P="cm2_round306c24a_source_g_15224_relation_backed_graph_family_support_and_representation_kernel";L=P+"_ledger.jsonl.gz";R=P+"_result.json"
C10L="cm2_round306c10_source_g_exact_graph_support_identity_rematerialization_exact_graph_support_ledger.jsonl.gz";C10R="cm2_round306c10_source_g_exact_graph_support_identity_rematerialization_result.json";C10V="cm2_round306c10_source_g_exact_graph_support_identity_rematerialization_verification.json";C10M="cm2_round306c10_source_g_exact_graph_support_identity_rematerialization_manifest.sha256"
C11AL="cm2_round306c11a_source_g_r235_side_sign_stratum_and_trace_kernel_ledger.jsonl.gz";C11AR="cm2_round306c11a_source_g_r235_side_sign_stratum_and_trace_kernel_result.json";C11AV="cm2_round306c11a_source_g_r235_side_sign_stratum_and_trace_kernel_verification.json";C11AM="cm2_round306c11a_source_g_r235_side_sign_stratum_and_trace_kernel_manifest.sha256"
C11BL="cm2_round306c11b_source_g_r242_side_incidence_trace_kernel_relation_theorem_ledger.jsonl.gz";C11BR="cm2_round306c11b_source_g_r242_side_incidence_trace_kernel_result.json";C11BV="cm2_round306c11b_source_g_r242_side_incidence_trace_kernel_verification.json";C11BM="cm2_round306c11b_source_g_r242_side_incidence_trace_kernel_manifest.sha256"
C12AL="cm2_round306c12a_source_g_rerouted_shared_side_kernel_ledger.jsonl.gz";C12AR="cm2_round306c12a_source_g_rerouted_shared_side_kernel_result.json";C12AV="cm2_round306c12a_source_g_rerouted_shared_side_kernel_verification.json";C12AM="cm2_round306c12a_source_g_rerouted_shared_side_kernel_manifest.sha256"
C14AL="cm2_round306c14a_source_g_graph_sheet_equality_and_partial_rematerialization_frontier_equality_ledger.jsonl.gz";C14AR="cm2_round306c14a_source_g_graph_sheet_equality_and_partial_rematerialization_frontier_result.json";C14AV="cm2_round306c14a_source_g_graph_sheet_equality_and_partial_rematerialization_frontier_verification.json";C14AM="cm2_round306c14a_source_g_graph_sheet_equality_and_partial_rematerialization_frontier_manifest.sha256"
C14BL="cm2_round306c14b_source_g_exact_partial_sheet_rematerialization_and_member_delta_exact_sheet_member_ledger.jsonl.gz";C14BR="cm2_round306c14b_source_g_exact_partial_sheet_rematerialization_and_member_delta_result.json";C14BV="cm2_round306c14b_source_g_exact_partial_sheet_rematerialization_and_member_delta_verification.json";C14BM="cm2_round306c14b_source_g_exact_partial_sheet_rematerialization_and_member_delta_manifest.sha256"
C16M="cm2_round306c16a_source_g_identity_representation_family_replay_member_identity_family_ledger.jsonl.gz";C16P="cm2_round306c16a_source_g_identity_representation_family_replay_representation_ledger.jsonl.gz";C16AR="cm2_round306c16a_source_g_identity_representation_family_replay_result.json";C16AV="cm2_round306c16a_source_g_identity_representation_family_replay_verification.json";C16AM="cm2_round306c16a_source_g_identity_representation_family_replay_manifest.sha256"
C16RL="cm2_round306c16b_source_g_relation_theorem_component_replay_positive_relation_ledger.jsonl.gz";C16BR="cm2_round306c16b_source_g_relation_theorem_component_replay_result.json";C16BV="cm2_round306c16b_source_g_relation_theorem_component_replay_verification.json";C16BM="cm2_round306c16b_source_g_relation_theorem_component_replay_manifest.sha256"
C17L="cm2_round306c17_source_g_15224_representation_pullback_kernel_ledger.jsonl.gz";C17R="cm2_round306c17_source_g_15224_representation_pullback_kernel_result.json";C17V="cm2_round306c17_source_g_15224_representation_pullback_kernel_verification.json";C17M="cm2_round306c17_source_g_15224_representation_pullback_kernel_manifest.sha256"
C23BR="cm2_round306c23b_source_g_9404_r292_component_union_and_10252_representation_semantic_kernel_result.json";C23BV="cm2_round306c23b_source_g_9404_r292_component_union_and_10252_representation_semantic_kernel_verification.json";C23BM="cm2_round306c23b_source_g_9404_r292_component_union_and_10252_representation_semantic_kernel_manifest.sha256"
PINS={C10L:"b7b2b02653a404060364b788b3e0ac8693d2d9d8d1c45e6109ca7f4400c4080c",C10M:"b7277863feb9edc5f35906b04af2a9a256becb7ee9f1f1df6558b897184029ca",C11AL:"87a37e007408adf667ae30a7575c928263512bf8a08cfd9e7144db11296680cd",C11AM:"b3222adb8ab4af54b61f6b1209c0d2dac8d95dbfee5a7b73decdd9a8cf06d421",C11BL:"37155fe874b8f4acd49773c013f4ec605a2f9388a0d1eb7443c88a731f1e0299",C11BM:"39eba276fa52653fddfe57e66f172df8bcf0aa330bcb3e6e2a2d5e2557a6bc50",C12AL:"12ae529eb5ccb53b75da1622c2c7b655a2acea6faf25d9018871a4fd079b35b9",C12AM:"be199019c5c4ba30c2728ae52ea95c7a65e4fa7dcc54145b78ece62fdbab0c5c",C14AL:"09aff7b141e519a1d7252e4ad8becdb668b8b12f84c99cdb69ffe43ae3529883",C14AM:"9a4b05b97453709afb579d5f25ecc4b74bc257a87b4172742468196fecd053c9",C14BL:"6f69b5e82377cde72e7223e86b518da12e19ef85b93a5706989ebb81ab78a6d6",C14BM:"2132aa257bf5cc0b90f0d39cd27eaa900c6965bc5fd6831ddedd79bbec34e678",C16M:"0686f987c6f7ab2ef247914fba45c94663f73fe7dcefc3bdb2ecbe43ea89166a",C16P:"47cc45de91a9d42be3d6b982cc044b39445d9db3682a8a9390be1ca9d1ffdfc1",C16AM:"597a9a402190989baa72f0e7955be376b3142850695096e2fdc6d651ce3ce7f4",C16RL:"532da85010d3cef78ae5c8e46bb1e14c15fb8271934697c823fa76236daec38b",C16BM:"2700fd9fd81a1572f76c9cb294babdde2da0727bb10f2568545d13a3fc0d35dc",C17L:"2d7a86fe0518ca2a003f1e70b3de56aa5eb80d7b1a176eb788333fc6ad75199c",C17M:"b926515f9942374c14ec9c7138afba303c55c73bfb325f9656dd0bfcf3e0a326",C23BR:"22eade6a1f152c4576d0f60d3515901e73b8fa6e7dae7a9a7bd4869b987da8a3",C23BM:"a9d8ecb93d719320894ef2520b697a67ef710a7c45339a72cc3f419461c802cf"}
SEALS=[(C10M,C10R,C10V,[C10L]),(C11AM,C11AR,C11AV,[C11AL]),(C11BM,C11BR,C11BV,[C11BL]),(C12AM,C12AR,C12AV,[C12AL]),(C14AM,C14AR,C14AV,[C14AL]),(C14BM,C14BR,C14BV,[C14BL]),(C16AM,C16AR,C16AV,[C16M,C16P]),(C16BM,C16BR,C16BV,[C16RL]),(C17M,C17R,C17V,[C17L]),(C23BM,C23BR,C23BV,[C23BR])]
class E(RuntimeError):pass
def need(value,label):
 if type(value)is not bool or not value:raise E(label)
def canon(value):return json.dumps(value,sort_keys=True,separators=(",",":"),ensure_ascii=True,allow_nan=False).encode("ascii")
def digest(value):return hashlib.sha256(canon(value)).hexdigest()
def file_hash(path):
 state=hashlib.sha256()
 with path.open("rb")as stream:
  while block:=stream.read(1048576):state.update(block)
 return state.hexdigest()
def check_row(row,label):body=dict(row);need(body.pop("row_sha256",None)==digest(body),label)
def check_result(result,label):body=dict(result);claimed=body.pop("result_sha256",None);need(type(claimed)is str and claimed==digest(body),label);return claimed
def rows(path)->Iterator[dict[str,Any]]:
 with gzip.open(path,"rb")as stream:
  for line in stream:
   need(line.endswith(b"\n"),"newline");raw=line[:-1];row=json.loads(raw);need(canon(row)==raw,"canonical");check_row(row,"row closure");yield row
def manifest_map(name):
 out={}
 for line in(ROOT/name).read_text().splitlines():parts=line.split(None,1);need(len(parts)==2,"manifest line");out[Path(parts[1].strip()).name]=parts[0]
 return out
def verification_pass(value):
 direct=value.get("status","");nested=value.get("independent_verifier",{}).get("status","");need((type(direct)is str and direct.startswith("PASS"))or(type(nested)is str and nested.startswith("PASS")),"independent verification");attack=value.get("coherent_attacks")or value.get("attack_harness")
 if attack is not None:need(attack.get("rejected",attack.get("coherent_attacks_rejected"))==attack.get("total",attack.get("coherent_attacks_total"))==8,"attacks")
def validate_sources():
 for name,sha in PINS.items():need(file_hash(ROOT/name)==sha,"pin:"+name)
 result_objects={}
 for manifest,result_name,verification_name,required in SEALS:
  listed=manifest_map(manifest)
  for name in [result_name,verification_name,*required]:need(name in listed and file_hash(ROOT/name)==listed[name],"manifest member:"+name)
  result=json.loads((ROOT/result_name).read_bytes());result_objects[result_name]=check_result(result,result_name);need(result["status"].startswith("PASS"),"result status");verification_pass(json.loads((ROOT/verification_name).read_bytes()))
 need(json.loads((ROOT/C23BR).read_bytes())["cumulative_global_member_support_credit"]==486812,"C23b boundary");return result_objects
def load_index(path,key):
 out={}
 for row in rows(ROOT/path):value=row[key];need(value not in out,"duplicate:"+path);out[value]=row
 return out
def identities():
 members={};representations={};owners=defaultdict(list)
 for row in rows(ROOT/C16M):
  if row["coarse_family"]in{"G2A","G2B"}:need(row["formal_credit"]["identity"]==row["formal_credit"]["family"]==1,"member credit");members[row["member_id"]]=row
 for row in rows(ROOT/C16P):
  if row["coarse_family"]in{"G2A","G2B"}:need(row["formal_credit"]["representation_identity"]==row["formal_credit"]["representation_owner_binding"]==1 and row["formal_credit"]["normalized_support"]==0,"representation credit");representations[row["representation_id"]]=row;owners[row["owner_member_id"]].append(row["representation_id"])
 need(Counter(row["coarse_family"]for row in members.values())=={"G2A":5264,"G2B":10128}and Counter(row["coarse_family"]for row in representations.values())=={"G2A":5264,"G2B":10128}and len(owners)==15392 and all(len(value)==1 for value in owners.values()),"identity census");return members,representations
def exact_support(role,source,graph,endpoint):
 if role=="C14A_EQ":
  certificate=source["graph_to_sheet_set_equality_certificate"];support=graph["base_domain_ast"];support_sha=graph["ast_sha256"]["base_domain_ast_sha256"];need(source["sheet_member_id"]==endpoint and source["graph_sheet_set_equality_credit"]==1 and certificate["current_sheet_support_equals_exact_base"]is True and certificate["projection_is_bijection"]is True and certificate["exact_base_domain_ast_sha256"]==support_sha,"C14A support");kind="G2A_EXISTING_EXACT_BASE_SHEET"
 elif role=="C14B_EQ":
  certificate=source["graph_to_new_sheet_set_equality_certificate"];support=source["exact_partial_base_ast"];support_sha=source["exact_partial_base_ast_sha256"];need(source["new_exact_sheet_member_id"]==endpoint and source["graph_sheet_set_equality_credit"]==1 and certificate["new_sheet_support_equals_exact_graph_projection"]is True and certificate["projection_is_bijection"]is True and certificate["new_exact_sheet_support_ast_sha256"]==support_sha,"C14B support");kind="G2A_NEW_EXACT_PARTIAL_BASE_SHEET"
 elif role in{"C11A","C12A"}:
  certificate=source["partition_branch_to_side_member_equivalence_certificate"];closure=source["closure_incidence_certificate"];support=source["exact_side_stratum_ast"];support_sha=source["exact_side_stratum_ast_sha256"];need(source["side_member_id"]==endpoint and source["scoped_credit"]=={"local_graph_side_physical_incidence":1,"one_sided_trace":1}and certificate["side_member_exact_support_equivalence_proved"]is True and certificate["exact_side_stratum_ast_sha256"]==support_sha and closure["closure_incidence_complete"]is True and source["one_sided_trace_certificate"]["every_graph_point_has_a_side_approach_path"]is True,"side support");kind="G2B_EXACT_STRICT_SIGN_SIDE_STRATUM"
 else:
  need(role=="C11B","source role");support=source["exact_side_carrier_ast"];support_sha=source["ast_sha256"]["exact_side_carrier_ast"];need(source["side_member_id"]==endpoint and source["local_graph_side_physical_incidence_proved"]is True and source["one_sided_trace_proved"]is True and source["formal_credit"]["local_graph_side_physical_incidence"]==source["formal_credit"]["one_sided_trace"]==1,"C11B support");kind="G2B_EXACT_R242_SIDE_CARRIER"
 need(digest(support)==support_sha,"support hash");return support,support_sha,kind
def verify(candidate):
 need(sys.flags.isolated==1 and sys.dont_write_bytecode is True,"runtime");raw=(candidate/R).read_bytes();result=json.loads(raw);need(canon(result)==raw,"result canonical");claimed=check_result(result,"result closure");need(result["status"]=="PASS_15224_RELATION_BACKED_GRAPH_FAMILY_MEMBER_SUPPORTS_AND_REPRESENTATION_SEMANTICS__168_NEGATIVE_G2B_PENDING"and(result["relation_backed_graph_family_member_count"],result["G2A_member_normalized_support_set_equality_credit"],result["G2A_primary_representation_set_equality_credit"],result["G2B_relation_backed_member_normalized_support_set_equality_credit"],result["G2B_relation_backed_primary_representation_set_equality_credit"],result["sealed_representation_pullback_credit_consumed"],result["typed_representation_semantic_credit"])==(15224,5264,5264,9960,9960,15224,15224),"result census");need((result["cumulative_global_member_support_credit"],result["remaining_global_member_support_debt"],result["graph_family_remaining_representation_semantic_debt"])==(502036,168,168)and result["remaining_global_member_debt_by_family"]=={"G2B_NEGATIVE_NONINCIDENCE_SIDE":168}and result["strict_nonpromotion"]=={"new_DSU_edges":0,"new_DSU_unions":0,"typed_global_support_ledger":0,"B1A":0,"B2":0,"maximality":0,"CM2":"NO-GO_FOR_CLAIM"}and result["input_pins"]==[{"filename":name,"sha256":sha}for name,sha in sorted(PINS.items())],"result boundary");seals=validate_sources();members,representations=identities();graphs=load_index(C10L,"graph_id");relations=load_index(C16RL,"row_id");sources={"C14A_EQ":load_index(C14AL,"row_id"),"C14B_EQ":load_index(C14BL,"row_id"),"C11A":load_index(C11AL,"row_id"),"C11B":load_index(C11BL,"row_id"),"C12A":load_index(C12AL,"row_id")};ledger=iter(rows(candidate/L));sequence=hashlib.sha256();seen=set();roles=Counter();families=Counter();row_kinds=Counter();ordinal=0
 for pullback in rows(ROOT/C17L):
  relation=relations[pullback["C16b_relation_ref"][1]];need(relation["row_sha256"]==pullback["C16b_relation_ref"][3]and(relation["graph_id"],relation["endpoint_member_id"],relation["relation_kind"])==(pullback["graph_id"],pullback["endpoint_member_id"],pullback["relation_kind"]),"relation join");endpoint=relation["endpoint_member_id"];need(endpoint not in seen,"endpoint uniqueness");seen.add(endpoint);member=members[endpoint];representation=representations[pullback["endpoint_canonical_representation_id"]];need(representation["row_id"]==pullback["C16a_endpoint_representation_ref"][1]and representation["row_sha256"]==pullback["C16a_endpoint_representation_ref"][3]and representation["owner_member_id"]==endpoint and(member["fresh_component_id"],member["base_root_id"],member["official_key_id"],member["coarse_family"])==(relation["endpoint_fresh_component_id"],relation["endpoint_base_root_id"],relation["endpoint_official_key_id"],pullback["endpoint_family"])and(representation["fresh_component_id"],representation["base_root_id"],representation["official_key_id"],representation["coarse_family"])==(member["fresh_component_id"],member["base_root_id"],member["official_key_id"],member["coarse_family"]),"identity join");graph=graphs[pullback["graph_id"]];need(graph["row_id"]==pullback["C10_exact_graph_support_ref"][1]and graph["row_sha256"]==pullback["C10_exact_graph_support_ref"][3],"graph join");role=relation["theorem_source_role"];source=sources[role][relation["theorem_source_ref"][1]];need(source["row_sha256"]==relation["theorem_source_ref"][3],"source join");support,support_sha,support_kind=exact_support(role,source,graph,endpoint);kind=relation["relation_kind"];certificate=pullback["pullback_certificate"];need(certificate["certificate_sha256"]==digest([relation["row_sha256"],graph["row_sha256"],pullback["C16a_endpoint_representation_ref"],representation["representation_id"],kind]),"certificate")
  if kind=="GRAPH_TO_SHEET":need(member["coarse_family"]=="G2A"and certificate["kind"]=="BIJECTIVE_GRAPH_PROJECTION_PULLBACK"and certificate["graph_sheet_set_equality"]is True and certificate["pullback_of_endpoint_representation_equals_exact_graph_support"]is True,"sheet pullback")
  else:need(kind=="GRAPH_TO_SIDE"and member["coarse_family"]=="G2B"and certificate["kind"]=="EXACT_BOUNDARY_CLOSURE_TRACE_PULLBACK"and certificate["local_physical_incidence"]is True and certificate["one_sided_trace"]is True and certificate["pullback_of_endpoint_representation_equals_exact_graph_boundary_stratum"]is True,"side pullback")
  theorem={"kind":"RELATION_BACKED_GRAPH_FAMILY_MEMBER_SUPPORT_AND_CANONICAL_REPRESENTATION_EQUALITY","support_kind":support_kind,"sealed_exact_support_authority":{"role":role,"row_id":source["row_id"],"row_sha256":source["row_sha256"],"support_ast_sha256":support_sha},"sealed_relation_replay":{"row_id":relation["row_id"],"row_sha256":relation["row_sha256"],"relation_kind":kind},"sealed_representation_pullback":{"row_id":pullback["row_id"],"row_sha256":pullback["row_sha256"],"induced_graph_pullback_representation_id":pullback["induced_graph_pullback_representation_id"],"certificate":certificate},"exact_source_support_equals_member_normalized_support":True,"C16_primary_canonical_endpoint_representation_binding_consumed":True,"canonical_endpoint_representation_set_equals_member_normalized_support":True,"sealed_pullback_semantics_consumed_without_new_DSU_edge":True};row_kind="G2A_GRAPH_TO_SHEET_MEMBER_AND_REPRESENTATION_SET_EQUALITY"if kind=="GRAPH_TO_SHEET"else"G2B_RELATION_BACKED_SIDE_MEMBER_AND_REPRESENTATION_SET_EQUALITY";body={"schema":"cm2.round306c24a.source-g-15224-relation-backed-graph-family-support-and-representation-kernel.v1.row.v1","ordinal":ordinal,"row_kind":row_kind,"coarse_family":member["coarse_family"],"member_id":endpoint,"fresh_component_id":member["fresh_component_id"],"base_root_id":member["base_root_id"],"official_key_id":member["official_key_id"],"canonical_representation_id":representation["representation_id"],"graph_id":graph["graph_id"],"normalized_support_ast":support,"normalized_support_ast_sha256":support_sha,"semantic_theorem_ast":theorem,"semantic_theorem_ast_sha256":digest(theorem),"source_bindings":{"C16a_member_row_sha256":member["row_sha256"],"C16a_representation_row_sha256":representation["row_sha256"],"C16b_relation_row_sha256":relation["row_sha256"],"C17_pullback_row_sha256":pullback["row_sha256"],"C23b_result_object_sha256":seals[C23BR]},"formal_credit":{"member_normalized_support_set_equality":1,"primary_representation_set_equality":1,"typed_representation_semantic_disposition":1,"sealed_representation_pullback_consumed":1},"strict_nonpromotion":{"DSU_edge":0,"DSU_union":0,"typed_global_support_ledger":0,"B1A":0,"B2":0,"maximality":0,"CM2":0}};expected={**body,"row_sha256":digest(body)};actual=next(ledger,None);need(actual==expected,"full row reconstruction");sequence.update(bytes.fromhex(actual["row_sha256"]));roles[role]+=1;families[member["coarse_family"]]+=1;row_kinds[row_kind]+=1;ordinal+=1
 need(next(ledger,None)is None and ordinal==len(seen)==15224 and roles=={"C11A":9422,"C14B_EQ":4432,"C14A_EQ":832,"C11B":528,"C12A":10}and families=={"G2A":5264,"G2B":9960},"replay census");need(result["source_role_census"]==dict(roles)and result["row_kind_census"]==dict(row_kinds),"result replay census");descriptor=result["ledger"];need(descriptor["filename"]==L and descriptor["row_count"]==15224 and descriptor["size"]==(candidate/L).stat().st_size and descriptor["sha256"]==file_hash(candidate/L)and descriptor["row_sequence_sha256"]==sequence.hexdigest()and descriptor["order"]=="C17_PULLBACK_LEDGER_ROW_ORDER","descriptor");return{"status":"PASS_INDEPENDENT_C24A_15224_RELATION_BACKED_GRAPH_FAMILY_FULL_RECONSTRUCTION__168_NEGATIVE_G2B_PENDING","result_sha256":claimed,"rows":15224,"G2A":5264,"G2B_relation_backed":9960}
def main():
 parser=argparse.ArgumentParser();parser.add_argument("--candidate-dir");args=parser.parse_args();candidate=ROOT if args.candidate_dir is None else Path(args.candidate_dir).resolve();print(canon(verify(candidate)).decode());return 0
if __name__=="__main__":raise SystemExit(main())
