"""Focused v159 front matter; the complete v158 introductions are archived."""
from pathlib import Path
import importlib.util
p=Path(__file__).resolve().parent.parent/'v158'/'frontmatter_v158.py'
spec=importlib.util.spec_from_file_location('front158',p)
old=importlib.util.module_from_spec(spec);spec.loader.exec_module(old)
I_ABSTRACT=old.I_ABSTRACT
I_INTRO=old.I_INTRO.replace(
    r'\subsection{Relation to the companion paper}',
    r'''The envelope has a universal property: it is the graded algebra generated
by the symmetric square of $\mathcal Hom(J^1L,L)$ with all rank-one
$(h+1)$st powers zero (Proposition~\ref{prop:universal-envelope-v159}).
For $h=1$ no auxiliary exponent is required. Jets, the Cartan quotient,
and scalar-trivial descent give the projective diagram directly from
the source extracted by the first relation.

\subsection{Relation to the companion paper}''')
II_TITLE='Intrinsic power geometry and the boundary of quadratic pencils'
II_ABSTRACT=r'''Multiplication in a determinant-apolar algebra gives balanced products
of symmetric minor ideals over every complex base algebra. Its complete
power graph at each rank is the relative space of complete quadrics
of the image bundle. For arbitrary symmetric pencils, power contacts
and finite syzygy maps recover elementary divisors and minimal indices.
We determine the embedded Hilbert limits of simultaneous ordinary
spectral collisions of arbitrary multiplicities. Their total spaces
are point blow-ups; their fibres are reduced nodal trees, and every
resolved power on each tail is a complete Veronese system of an explicit
degree. Residual pencils parametrize positive-dimensional families of
distinct limits over the same original pencil, giving a lower bound
for fibres of the normalized incidence modification. The native
interpretation uses a functorial algebra bundle extracted from the
first relation of the unmarked failure algebra, not a chosen section
of its auxiliary normalization fibre.'''
II_INTRO=r'''\section{Introduction}
\label{sec:paper-ii-v159}
A compactification records more than a limiting pencil when different
smoothing directions produce different resolved curves. We study this
difference through multiplication powers in the finite algebra
\[
 B_h(V)=\Sym(\Sym^2V)/\langle(v^2)^{h+1}:v\in V\rangle,
 \qquad h\geq1.
\]
Here $V$ is a complex vector space of dimension $n$. For a symmetric
matrix $A$, write $J_p(A)$ for the ideal generated by the coefficients
of its $p$th power. Its universal identity is
\[
 J_{hq+s}(A)=I_q(A)^{h-s}I_{q+1}(A)^s,\qquad 0\leq s<h,
\]
where $I_q$ denotes the ideal of $q$-minors
(Theorem~\ref{thm:universal-power-v157}). This is equality of ordinary
ideals, including over nonreduced bases. The proof identifies the
coefficient representation and uses classical invariant-ideal
balancing. We make its classical inputs and its precise apolar
interpretation explicit in Section~\ref{sec:power-conventions-v158}.

\subsection{Embedded boundary fibres}
Let a family of regular pencils over $\C[[\tau]]$ have generically
simple spectrum and simultaneous ordinary transverse clusters of
multiplicities $c_a$ in its special fibre. Put $r_a=n-c_a$.
At a cluster, the symmetric Schur complement has the form
\[
 S_a=z_a C_a+\tau D_a+O((z_a,\tau)^2),\qquad
 \det(\alpha C_a+\beta D_a)\text{ squarefree},
\]
with $C_a$ nonsingular. The schematic closure of the lifted generic
pencil in complete quadrics is the blow-up of the cluster points in
the total pencil surface. Its special fibre is a reduced nodal main
curve with one tail at each cluster. The tail is the lifted residual
pencil $[\alpha C_a+\beta D_a]$, marked by its attachment $[C_a]$
(Theorem~\ref{thm:ordinary-fibres-v159}). This statement includes
simultaneous clusters of every allowed multiplicity and is unchanged
by higher-order perturbations with fixed special pencil and first
normal jets.

All multiplication systems on those tails are determined. For
$1\leq p\leq hn$, set
\[
 b_a=(p-hr_a)_+,\qquad s_p=(p-h(n-1))_+,\qquad
 \delta_{a,p}=b_a-c_a s_p.
\]
The exact local power ideal and its resolved tail map are
\[
 J_p(A)=(z_a,\tau)^{\delta_{a,p}}(\det S_a)^{s_p},
 \qquad F_a\longrightarrow\Pj^{\delta_{a,p}}
               \text{ the complete Veronese map}.
\]
A degree-zero map is constant. In particular
$J_{h(n-c_a)+1}=(z_a,\tau)$: one multiplication ideal selects the
exceptional component, and the remaining products give all its linear
systems. This is not the formal pullback of an unrelated flat algebra.

For a fixed semisimple pencil $R_0$, the residual lines through each
$[C_a]$ give a family of distinct embedded limits. If
$\rho:\widehat G\to\Gr(2,\Sym^2V)$ is the normalized Hilbert incidence
modification, then
\[
 \dim\rho^{-1}(R_0)\geq
             \sum_a\left(\binom{c_a+1}{2}-2\right)
\]
(Theorem~\ref{thm:boundary-moduli-v159}). The parameter spaces, their
flat embedded families and their smoothing realizations are explicit.
This is a modular family inside the fibre, not a classification of
all its components. Already a semisimple triple collision gives a
four-dimensional family with the same limiting failure algebra.

\subsection{All ranks and singular pencils}
On the rank-$r$ locus retain the powers through $hr$, including the
last one. The last power is the degree-$2h$ Pluecker image of the
image $r$-plane. The simultaneous graph is precisely
$\mathrm{CQ}(\mathcal U)\to\Gr(r,V)$, without further normalization
(Theorem~\ref{thm:all-rank-graph-v158}). Complete quadrics and their
orbit strata are classical; the theorem realizes their full projection
and scheme structure by powers in one algebra.

For a symmetric pencil of normal rank $r$, the kernel splitting
$\bigoplus_a\OO(-\varepsilon_a)$ is read from finitely many coefficient
syzygy maps. If their nullities are $\kappa_j$, then
\[
 \#\{a:\varepsilon_a=j\}=\kappa_j-2\kappa_{j-1}+\kappa_{j-2}.
\]
The relative boundary contacts give the positive Smith exponents,
with their spectral positions, and satisfy
\[
 \sum_{i=1}^{r-1}(r-i)\deg D_i+
          2\deg(\Lambda\to\Gr(r,V))=r,
 \qquad\deg(\Lambda\to\Gr(r,V))=\sum_a\varepsilon_a.
\]
Together these recover all complex congruence data, including singular
pencils (Theorem~\ref{thm:singular-complete-data-v158}). The complex
Kronecker classification is a classical input to this interpretation.
The ordinary-collision Hilbert theorem is a separate assertion with
its stated transverse hypotheses, not a claim about arbitrary singular
special fibres.

\subsection{Intrinsic origin and logical dependencies}
The companion paper extracts an oriented source projective space from
the first relation of an unmarked sharp failure algebra, before its
last step recovering the pencil coefficient line. The first-jet bundle
and a Cartan quotient on that source construct a scalar-normalized
algebra bundle and its projective multiplication diagram
(Theorem~\ref{thm:intrinsic-envelope-v158} and
Proposition~\ref{prop:universal-envelope-v159}). It is not a preferred
subquotient of the original algebra, and it does not choose an
$n$-plane in an auxiliary coefficient complement of dimension $n^2-1$.
The case $h=1$ gives a distinguished diagram without an exponent choice.

The ideal, graph, all-pencil and boundary proofs here start with $V$
and a pencil and do not use the sharp inverse. Only their interpretation
as functors of the original unmarked failure algebra invokes that
companion. Conversely, the sharp inverse and source descent do not
use the present boundary theorems. The two core proofs are independent;
the intrinsic-envelope application links them with these inputs stated.

The later sections preserve binary normalization and conductor theory,
all-collision incidence charts and reciprocal-fibre homology. The
multiplier formula is explicitly a consequence of the classical
symmetric-determinantal calculation, not an independent novelty claim.
The theorem-level comparison with Ballico's failure-locus paper
\cite{Ballico93} remains limited by unavailable full text; no assertion
of historical nonanticipation follows from that absence.
'''
MASTER_ABSTRACT=I_ABSTRACT+r'''
The companion identifies all-rank power graphs and singular-pencil
invariants, computes simultaneous ordinary-collision Hilbert fibres
with every tail power map, and gives positive-dimensional residual-pencil
moduli in an incidence fibre. This master preserves the complete
mathematical contents of the two focused papers; it is not a third
submission.'''
MASTER_INTRO=old.MASTER_INTRO+r'''
Theorem~\ref{thm:ordinary-fibres-v159} extends the corank-two calculation
to simultaneous ordinary clusters of arbitrary multiplicities and
higher-order perturbations. It computes the exact total-base power
ideals, the reduced nodal fibre and every tail linear system.
Theorem~\ref{thm:boundary-moduli-v159} constructs a modular family of
distinct such limits over a fixed semisimple pencil and proves a
positive lower bound for the incidence-fibre dimension.
Proposition~\ref{prop:universal-envelope-v159} supplies the universal
property of the intrinsic source-normalized algebra. These additions
leave every predecessor mathematical statement and proof in place.
'''
# The predecessor already contains the complete cited bibliography and disclosures.
BIB=''
DISCLOSURE=''
